import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, CircleX, FileBadge2, RefreshCcw } from "lucide-react";
import { getGeneratedDocumentByVerificationToken } from "@/lib/admin-documents";
import { formatDateFr } from "@/lib/format";

export const dynamic = "force-dynamic";
export const metadata:Metadata={title:"Vérification d’un document"};
const statusLabels={active:"Actif",replaced:"Remplacé",deleted:"Annulé",cancelled:"Annulé"} as const;
export default async function VerifyDocumentPage({params}:{params:Promise<{token:string}>}){const{token}=await params;const document=await getGeneratedDocumentByVerificationToken(token).catch(()=>null);const valid=document?.status==="active";return <main className="min-h-screen bg-ivory px-4 py-12 text-navy"><section className="mx-auto max-w-2xl overflow-hidden rounded-[2rem] bg-white shadow-premium"><header className="bg-navy p-8 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Accès Canada</p><h1 className="mt-3 font-display text-4xl font-black">Authenticité du document</h1></header><div className="p-8">{document?<><div className={`flex items-center gap-3 rounded-2xl p-5 ${valid?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-900"}`}>{valid?<CheckCircle2 className="h-8 w-8"/>:<RefreshCcw className="h-8 w-8"/>}<div><p className="font-black">Document {statusLabels[document.status]}</p><p className="text-sm">Enregistrement officiel retrouvé dans le registre Accès Canada.</p></div></div><dl className="mt-7 grid gap-4 rounded-2xl border border-navy/10 p-6 sm:grid-cols-2"><Item label="Numéro" value={document.document_number}/><Item label="Type" value={document.document_label}/><Item label="Création" value={formatDateFr(document.issued_at||document.created_at)}/><Item label="Version" value={String(document.version)}/><Item label="Statut" value={statusLabels[document.status]}/><Item label="Empreinte" value={`${document.authenticity_hash.slice(0,12)}…`}/></dl>{document.status!=="active"?<p className="mt-5 rounded-2xl bg-canada/8 p-4 text-sm font-bold text-canada">Ce document n’est plus la version active. Demandez la version la plus récente à Accès Canada.</p>:null}</>:<div className="flex items-start gap-3 rounded-2xl bg-red-50 p-5 text-red-900"><CircleX className="h-8 w-8 shrink-0"/><div><p className="font-black">Document non authentifié</p><p className="text-sm">Le code est inconnu ou ne correspond à aucun document officiel.</p></div></div>}<div className="mt-7 flex items-center gap-3 border-t border-navy/10 pt-6"><FileBadge2 className="text-gold"/><p className="text-sm text-navy/60">Votre chemin vers le Canada, notre engagement.</p></div><Link href="/" className="mt-6 inline-flex rounded-xl bg-navy px-5 py-3 font-black text-white">Retour à l’accueil</Link></div></section></main>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-black uppercase tracking-wider text-navy/45">{label}</dt><dd className="mt-1 break-words font-bold">{value}</dd></div>}
