import {NextResponse} from "next/server";
import {isAdminAuthenticated,getAdminIdentity} from "@/lib/admin-auth";
import {getClient} from "@/lib/admin-data";
import {listClientUploads,shareClientUpload} from "@/lib/client-portal";
import {prepareClientDocumentDelivery} from "@/lib/client-document-delivery";
import {notifyClient} from "@/lib/production-workflow";
import {createAuditLog,createNotification} from "@/lib/platform-v2";

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!(await isAdminAuthenticated()))return NextResponse.json({message:"Non autorisé."},{status:401});
  try{const{id}=await params;const body=await request.json() as{clientId?:string;deadline?:string|null};if(!body.clientId)return NextResponse.json({message:"Dossier client requis."},{status:400});const[client,uploads,identity]=await Promise.all([getClient(body.clientId),listClientUploads(body.clientId,true),getAdminIdentity()]);const upload=uploads.find(item=>item.id===id&&item.status==="active");if(!client||!upload)return NextResponse.json({message:"Document ou client introuvable."},{status:404});const delivery=await prepareClientDocumentDelivery({clientId:client.id,fileName:upload.file_name,category:upload.category,deadline:body.deadline});const shared=await shareClientUpload({clientId:client.id,uploadId:id,...delivery});const portalUrl=`${(process.env.NEXT_PUBLIC_SITE_URL||"https://acces-canada.vercel.app").replace(/\/$/,"")}/client/documents`;const emailSent=await notifyClient(client,"Accès Canada - nouveau document disponible",`Bonjour ${client.full_name},\n\nUn nouveau document a été déposé dans votre espace client Accès Canada.\n\nDocument : ${upload.file_name}\n${delivery.summary}\n\nVeuillez vous connecter afin de consulter les instructions : ${portalUrl}\n\nL’équipe Accès Canada`);await Promise.all([createNotification({clientId:client.id,type:"client_document_shared",title:"Document envoyé au client",message:`${upload.file_name} est disponible dans le portail de ${client.full_name}.`,severity:"success",href:`/admin/clients/${client.id}`,dedupeKey:`shared-${id}-${shared.shared_at}`}),createAuditLog({actorId:identity?.id,action:"share",entityType:"client_uploaded_documents",entityId:id,clientId:client.id,summary:`${upload.file_name} envoyé au portail client.`,metadata:{deadline:delivery.deadline,actions:delivery.actions,emailSent}})]);return NextResponse.json({document:shared,delivery,emailSent,message:emailSent?"Document déposé dans le portail et notification envoyée.":"Document déposé dans le portail. Le courriel n’a pas été envoyé : configuration SMTP incomplète."});}catch(error){console.error("Envoi document au portail",error);return NextResponse.json({message:error instanceof Error?error.message:"Envoi impossible."},{status:500});}
}
