import "server-only";
import { assertMonthlyAiBudget,recordAiUsage } from "@/lib/ai-usage";

export async function prepareClientDocumentDelivery(input:{clientId:string;fileName:string;category:string;analysis?:string|null;deadline?:string|null}){
  const token=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL||"gpt-5.4";
  if(!token)return{summary:`Un nouveau document « ${input.fileName} » est disponible dans votre espace client Accès Canada.`,actions:["Consulter le document en entier.","Suivre les instructions indiquées.","Poser une question dans la messagerie sécurisée en cas de doute."],deadline:input.deadline||null};
  await assertMonthlyAiBudget();const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(45000),body:JSON.stringify({model,response_format:{type:"json_schema",json_schema:{name:"instructions_client",strict:true,schema:{type:"object",additionalProperties:false,properties:{summary:{type:"string"},actions:{type:"array",items:{type:"string"}}},required:["summary","actions"]}}},messages:[{role:"system",content:"Tu es Julie, assistante administrative d’Accès Canada. Prépare un résumé client simple, professionnel et factuel. N’invente aucune exigence, échéance ou décision juridique. Donne 2 à 6 actions concrètes uniquement à partir des renseignements fournis."},{role:"user",content:`Document: ${input.fileName}\nCatégorie: ${input.category}\nAnalyse disponible: ${input.analysis||"Aucune analyse détaillée."}`} ]})});
  if(!response.ok)throw new Error(`Résumé client impossible (${response.status}).`);const body=await response.json() as{choices?:Array<{message?:{content?:string}}> ;usage?:{prompt_tokens?:number;completion_tokens?:number}};const raw=body.choices?.[0]?.message?.content||"{}";const parsed=JSON.parse(raw) as{summary?:string;actions?:string[]};if(!parsed.summary?.trim())throw new Error("Julie n’a produit aucun résumé client.");await recordAiUsage({clientId:input.clientId,feature:"client_document_delivery",model,inputTokens:body.usage?.prompt_tokens,outputTokens:body.usage?.completion_tokens}).catch(()=>undefined);return{summary:parsed.summary.trim(),actions:(parsed.actions||[]).map(item=>item.trim()).filter(Boolean).slice(0,8),deadline:input.deadline||null};
}
