export type LibraryItem={id:string;title:string;category:"lettre"|"courriel"|"procedure"|"guide"|"checklist"|"pdf";description:string|null;content:string|null;file_path:string|null;status:"draft"|"active"|"archived";tags:string[];is_favorite:boolean;version:number;parent_template_id:string|null;archived_at:string|null;created_by:string;created_at:string;updated_at:string};
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase bibliothèque manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function error(response:Response){throw new Error(`Bibliothèque Supabase (${response.status}) : ${await response.text()}`);}
export async function listLibraryItems(){const{url}=config();const response=await fetch(`${url}/rest/v1/internal_document_library?select=*&order=updated_at.desc`,{headers:headers(),cache:"no-store"});if(!response.ok)await error(response);return await response.json() as LibraryItem[];}
export async function getLibraryItem(id:string){const{url}=config();const response=await fetch(`${url}/rest/v1/internal_document_library?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,{headers:headers(),cache:"no-store"});if(!response.ok)await error(response);return((await response.json()) as LibraryItem[])[0]||null;}
export async function createLibraryItem(input:{title:string;category:LibraryItem["category"];description:string;content:string;tags:string[];createdBy:string;version?:number;parentTemplateId?:string|null}){const{url}=config();const response=await fetch(`${url}/rest/v1/internal_document_library`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({title:input.title,category:input.category,description:input.description||null,content:input.content||null,tags:input.tags,created_by:input.createdBy,status:"active",version:input.version||1,parent_template_id:input.parentTemplateId||null})});if(!response.ok)await error(response);return((await response.json()) as LibraryItem[])[0];}
export async function updateLibraryItem(id:string,patch:Partial<Pick<LibraryItem,"is_favorite"|"status"|"title"|"description"|"content"|"tags"|"archived_at">>){const{url}=config();const response=await fetch(`${url}/rest/v1/internal_document_library?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)await error(response);return((await response.json()) as LibraryItem[])[0];}
export async function duplicateLibraryItem(id:string,createdBy:string){const source=await getLibraryItem(id);if(!source)throw new Error("Modèle introuvable.");return createLibraryItem({title:`${source.title} — copie`,category:source.category,description:source.description||"",content:source.content||"",tags:source.tags,createdBy,version:source.version+1,parentTemplateId:source.parent_template_id||source.id});}
