import "server-only";
import { createHash } from "node:crypto";
import { getClient } from "@/lib/admin-data";
import { downloadClientFile,type ClientUploadedDocument } from "@/lib/client-portal";
import { reconcileClientDocumentState } from "@/lib/document-state";
import { createAuditLog } from "@/lib/platform-v2";
import { classifyExtractedDocument, normalizedDocumentName, type IntelligentDocumentResult } from "@/lib/document-intelligence";
import { ensureJulieApproval } from "@/lib/julie";

export type DocumentAnalysis={id:string;upload_id:string;client_id:string|null;status:"pending"|"processing"|"completed"|"failed"|"manual_review";detected_type:string|null;suggested_name:string|null;suggested_category:string|null;summary:string|null;extracted_text:string|null;extracted_fields:Record<string,unknown>;confidence:number|null;model:string|null;error_message:string|null;created_at:string;updated_at:string};
const categories=new Set(["a_verifier","identite","passeport","refus_ircc","formulaires_ircc","situation_financiere","emploi_commerce","attaches_familiales","garant_financier","correspondance","acces_canada"]);
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(r:Response){if(!r.ok)throw new Error(await r.text());return r;}
function clean(value:unknown){return typeof value==="string"?value.trim():"";}

function fallback(name:string,clientName:string,code="AI_NOT_CONFIGURED",detail="OPENAI_API_KEY n’est pas disponible dans l’environnement de production."){const result=classifyExtractedDocument("",name,clientName);return{...result,summary:`Analyse intelligente non exécutée (${code}). ${detail}`,suggested_category:"a_verifier",extracted_fields:{...result.extracted_fields,diagnostic_code:code,diagnostic_detail:detail},confidence:0};}
function aiConfig(){if(process.env.OPENAI_API_KEY)return{url:"https://api.openai.com/v1/responses",token:process.env.OPENAI_API_KEY,model:process.env.OPENAI_VISION_MODEL||process.env.OPENAI_MODEL||"gpt-5.4"};return null;}
async function intelligent(bytes:Buffer,file:ClientUploadedDocument,clientName:string):Promise<IntelligentDocumentResult>{
  const ai=aiConfig();if(!ai)return fallback(file.file_name,clientName);
  const base64=bytes.toString("base64"),isImage=file.file_type?.startsWith("image/");
  const content=isImage?[{type:"input_text",text:`Analyse le contenu. Le client actuellement sélectionné est ${clientName}.`},{type:"input_image",image_url:`data:${file.file_type};base64,${base64}`}]:[{type:"input_text",text:`Analyse le contenu natif puis visuel/OCR si nécessaire. Le client actuellement sélectionné est ${clientName}.`},{type:"input_file",filename:file.file_name,file_data:`data:${file.file_type||"application/pdf"};base64,${base64}`}];
  const instructions=`Tu classes les documents administratifs d'Accès Canada à partir du CONTENU, jamais principalement du nom du fichier. Retourne seulement un JSON: detected_type, suggested_category, summary, extracted_text, extracted_fields, confidence. Catégories: ${[...categories].join(", ")}. extracted_fields contient seulement les valeurs visibles parmi holder_name,holder_role (client,garant,invitant,autre,a_confirmer),holder_confidence,client_match_confidence,country,document_number,birth_date,expiry_date,bank,period (YYYY-MM),currency,opening_balance,closing_balance,decision_date,form_number,evidence. Distingue le titulaire du client sélectionné. Un relevé d'une autre personne est garant_financier uniquement si le contenu soutient ce rôle, sinon a_verifier. Si le type ou titulaire est incertain: a_verifier. N'invente aucune valeur.`;
  let response:Response|null=null;let lastDetail="";
  for(let attempt=1;attempt<=3;attempt++){try{response=await fetch(ai.url,{method:"POST",headers:{Authorization:`Bearer ${ai.token}`,"Content-Type":"application/json"},body:JSON.stringify({model:ai.model,instructions,input:[{role:"user",content}],max_output_tokens:3200}),signal:AbortSignal.timeout(45000)});if(response.ok)break;lastDetail=(await response.text()).slice(0,500);if(![408,429,500,502,503,504].includes(response.status))break;}catch(error){lastDetail=error instanceof Error?error.message:"Délai dépassé";response=null;}}
  if(!response?.ok){const status=response?.status||0,code=status===401||status===403?"AI_AUTH_INVALID":status===429?"AI_QUOTA_OR_RATE_LIMIT":status>=500?"AI_PROVIDER_UNAVAILABLE":status===0?"AI_TIMEOUT_OR_NETWORK":"AI_REQUEST_REJECTED";return fallback(file.file_name,clientName,code,`Appel ${ai.url} refusé ou interrompu${status?` (HTTP ${status})`:""}. ${lastDetail}`);}
  const body=await response.json() as{output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=body.output_text||body.output?.flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("")||"{}";
  const parsed=JSON.parse(text.replace(/^```json\s*|\s*```$/g,"")) as Partial<IntelligentDocumentResult>;const confidence=Math.max(0,Math.min(1,Number(parsed.confidence)||0));const extracted_fields=parsed.extracted_fields&&typeof parsed.extracted_fields==="object"?parsed.extracted_fields:{};const category=categories.has(String(parsed.suggested_category))?String(parsed.suggested_category):"a_verifier";
  const result:IntelligentDocumentResult={detected_type:clean(parsed.detected_type)||"Document a verifier",suggested_name:file.file_name,suggested_category:confidence>=.65?category:"a_verifier",summary:clean(parsed.summary)||"Analyse à confirmer.",extracted_text:clean(parsed.extracted_text).slice(0,30000),extracted_fields,confidence,model:ai.model};result.suggested_name=normalizedDocumentName(result,file.file_name);return result;
}

async function isDuplicate(clientId:string,uploadId:string,hash:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/document_analyses?client_id=eq.${encodeURIComponent(clientId)}&upload_id=neq.${encodeURIComponent(uploadId)}&extracted_fields->>content_sha256=eq.${hash}&select=id,upload_id&limit=1`,{headers:headers(),cache:"no-store"}));return((await response.json()) as unknown[]).length>0;}
export async function analyzeClientUpload(upload:ClientUploadedDocument){
  const{url}=config();const pending=await checked(await fetch(`${url}/rest/v1/document_analyses`,{method:"POST",headers:headers("resolution=merge-duplicates,return=representation"),body:JSON.stringify({upload_id:upload.id,client_id:upload.client_id,status:"processing",updated_at:new Date().toISOString()})}));const row=(await pending.json() as DocumentAnalysis[])[0];
  try{const[downloaded,client]=await Promise.all([downloadClientFile(upload.client_id,upload.id),getClient(upload.client_id)]);if(!downloaded||!client)throw new Error("Fichier ou client introuvable.");const contentHash=createHash("sha256").update(downloaded.bytes).digest("hex");const duplicate=await isDuplicate(upload.client_id,upload.id,contentHash);let result=await intelligent(downloaded.bytes,upload,client.full_name);result={...result,extracted_fields:{...result.extracted_fields,content_sha256:contentHash,duplicate}};if(duplicate){result={...result,suggested_category:"a_verifier",confidence:Math.min(result.confidence,.59),summary:`Doublon détecté. ${result.summary}`};}const status=result.confidence>=.65&&result.suggested_category!=="a_verifier"?"completed":"manual_review";const saved=await checked(await fetch(`${url}/rest/v1/document_analyses?id=eq.${row.id}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({...result,status,updated_at:new Date().toISOString()})}));
    await checked(await fetch(`${url}/rest/v1/client_uploaded_documents?id=eq.${upload.id}`,{method:"PATCH",headers:headers(),body:JSON.stringify({file_name:String(result.suggested_name||upload.file_name).slice(0,240),category:status==="completed"?result.suggested_category:"a_verifier",updated_at:new Date().toISOString()})}));
    const state=await reconcileClientDocumentState(upload.client_id);let approvalId:string|undefined;if(status==="manual_review"){const approval=await ensureJulieApproval({clientId:upload.client_id,actionType:"document_review",dedupeKey:upload.id,title:`Document à vérifier — ${result.suggested_name}`,description:`${result.summary} Catégorie proposée : ${result.suggested_category}. Confiance : ${Math.round(result.confidence*100)} %.`,payload:{uploadId:upload.id,analysisId:row.id,detectedType:result.detected_type,suggestedCategory:result.suggested_category,confidence:result.confidence,diagnosticCode:result.extracted_fields.diagnostic_code||null}});approvalId=approval.id;}await createAuditLog({actorId:"julie",actorType:"system",action:"analyze",entityType:"client_uploaded_documents",entityId:upload.id,clientId:upload.client_id,summary:`Julie a analysé ${upload.file_name} par contenu : ${status==="completed"?"classé":"validation requise"}.`,metadata:{detectedType:result.detected_type,category:result.suggested_category,confidence:result.confidence,duplicate,state,approvalId}});return(await saved.json() as DocumentAnalysis[])[0];
  }catch(error){await fetch(`${url}/rest/v1/document_analyses?id=eq.${row.id}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status:"failed",error_message:error instanceof Error?error.message:"Analyse impossible",updated_at:new Date().toISOString()})});throw error;}}
export async function listDocumentAnalyses(clientId:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/document_analyses?client_id=eq.${encodeURIComponent(clientId)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}));return await r.json() as DocumentAnalysis[];}
export async function approveDocumentReview(input:{uploadId:string;analysisId?:string;clientId:string;reviewedBy:string}){const{url}=config();const filter=input.analysisId?`id=eq.${encodeURIComponent(input.analysisId)}`:`upload_id=eq.${encodeURIComponent(input.uploadId)}`;const analysis=await checked(await fetch(`${url}/rest/v1/document_analyses?${filter}&select=*&limit=1`,{headers:headers(),cache:"no-store"})).then(r=>r.json() as Promise<DocumentAnalysis[]>).then(rows=>rows[0]);if(!analysis)throw new Error("Analyse documentaire introuvable.");if(!analysis.suggested_category||analysis.suggested_category==="a_verifier")throw new Error("Choisissez d’abord une catégorie dans le gestionnaire documentaire.");await checked(await fetch(`${url}/rest/v1/client_uploaded_documents?id=eq.${encodeURIComponent(input.uploadId)}&client_id=eq.${encodeURIComponent(input.clientId)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({category:analysis.suggested_category,file_name:analysis.suggested_name,updated_at:new Date().toISOString()})}));await checked(await fetch(`${url}/rest/v1/document_analyses?id=eq.${encodeURIComponent(analysis.id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status:"completed",reviewed_at:new Date().toISOString(),reviewed_by:input.reviewedBy,updated_at:new Date().toISOString()})}));return reconcileClientDocumentState(input.clientId);}
