import "server-only";
import { downloadClientFile,type ClientUploadedDocument } from "@/lib/client-portal";
import { createAuditLog } from "@/lib/platform-v2";
export type DocumentAnalysis={id:string;upload_id:string;client_id:string|null;status:"pending"|"processing"|"completed"|"failed"|"manual_review";detected_type:string|null;suggested_name:string|null;suggested_category:string|null;summary:string|null;extracted_text:string|null;extracted_fields:Record<string,unknown>;confidence:number|null;model:string|null;error_message:string|null;created_at:string;updated_at:string};
const categories=new Set(["identite","passeport","refus_ircc","formulaires_ircc","situation_financiere","emploi_commerce","attaches_familiales","garant_financier","correspondance","acces_canada"]);
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(r:Response){if(!r.ok)throw new Error(await r.text());return r;}
function fallback(name:string){const n=name.toLocaleLowerCase("fr-CA");const rules:Array<[RegExp,string,string]>=[[/passeport|passport/,"Passeport","passeport"],[/refus|decision|ircc/,"Décision ou refus IRCC","refus_ircc"],[/relev[eé].*banc|bank|financ|mobile.money/,"Document financier","situation_financiere"],[/emploi|travail|work.permit|commerce|salaire/,"Document d’emploi ou de commerce","emploi_commerce"],[/caq|csq|imm\s?\d{4}|formulaire/,"Formulaire ou certificat d’immigration","formulaires_ircc"],[/identit|naissance|mariage|certificat/,"Document d’identité ou d’état civil","identite"],[/garant|prise.en.charge/,"Document du garant financier","garant_financier"],[/lettre|courriel|correspond/,"Correspondance","correspondance"]];const found=rules.find(([rx])=>rx.test(n));return{detected_type:found?.[1]||"Document à vérifier",suggested_category:found?.[2]||"correspondance",suggested_name:name.replace(/[^\p{L}\p{N}._ -]/gu,"").trim(),summary:"Classement préliminaire établi à partir du nom du fichier. Vérification administrative recommandée.",extracted_text:"",extracted_fields:{},confidence:found?.[0]?0.72:0.35};}
async function intelligent(bytes:Buffer,file:ClientUploadedDocument){const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return fallback(file.file_name);const model=process.env.OPENAI_VISION_MODEL||process.env.OPENAI_MODEL||"gpt-5.4";const base64=bytes.toString("base64"),isImage=file.file_type?.startsWith("image/");const content=isImage?[{type:"input_text",text:"Analyse ce document administratif."},{type:"input_image",image_url:`data:${file.file_type};base64,${base64}`}]:[{type:"input_text",text:"Analyse ce document administratif."},{type:"input_file",filename:file.file_name,file_data:`data:${file.file_type||"application/pdf"};base64,${base64}`}];const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,instructions:`Tu aides au classement administratif d’Accès Canada. Extrais seulement les informations visibles. Retourne exclusivement un objet JSON avec: detected_type, suggested_name, suggested_category, summary, extracted_text, extracted_fields, confidence. suggested_category doit être l’une de: ${[...categories].join(", ")}. confidence entre 0 et 1. Ne rends aucun avis juridique.`,input:[{role:"user",content}],max_output_tokens:2200})});if(!r.ok)throw new Error(`OCR indisponible (${r.status}).`);const body=await r.json() as{output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=body.output_text||body.output?.flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("")||"{}";const parsed=JSON.parse(text.replace(/^```json\s*|\s*```$/g,"")) as ReturnType<typeof fallback>;return{...parsed,suggested_category:categories.has(parsed.suggested_category)?parsed.suggested_category:"correspondance",confidence:Math.max(0,Math.min(1,Number(parsed.confidence)||0)),model};}
export async function analyzeClientUpload(upload:ClientUploadedDocument){const{url}=config();const pending=await checked(await fetch(`${url}/rest/v1/document_analyses`,{method:"POST",headers:headers("resolution=merge-duplicates,return=representation"),body:JSON.stringify({upload_id:upload.id,client_id:upload.client_id,status:"processing",updated_at:new Date().toISOString()})}));const row=(await pending.json() as DocumentAnalysis[])[0];try{const downloaded=await downloadClientFile(upload.client_id,upload.id);if(!downloaded)throw new Error("Fichier introuvable.");const result=await intelligent(downloaded.bytes,upload),status=result.confidence>=.6?"completed":"manual_review";const saved=await checked(await fetch(`${url}/rest/v1/document_analyses?id=eq.${row.id}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({...result,status,updated_at:new Date().toISOString()})}));if(result.confidence>=.85){await fetch(`${url}/rest/v1/client_uploaded_documents?id=eq.${upload.id}`,{method:"PATCH",headers:headers(),body:JSON.stringify({file_name:String(result.suggested_name||upload.file_name).slice(0,240),category:result.suggested_category,updated_at:new Date().toISOString()})});}await createAuditLog({actorId:"julie",actorType:"system",action:"analyze",entityType:"client_uploaded_documents",entityId:upload.id,clientId:upload.client_id,summary:`Julie a analysé et classé le document ${upload.file_name}.`,metadata:{detectedType:result.detected_type,category:result.suggested_category,confidence:result.confidence}});return(await saved.json() as DocumentAnalysis[])[0];}catch(error){await fetch(`${url}/rest/v1/document_analyses?id=eq.${row.id}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status:"failed",error_message:error instanceof Error?error.message:"Analyse impossible",updated_at:new Date().toISOString()})});throw error;}}
export async function listDocumentAnalyses(clientId:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/document_analyses?client_id=eq.${encodeURIComponent(clientId)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}));return await r.json() as DocumentAnalysis[];}
