import type { Appointment } from "@/lib/booking-shared";
import type { ClientPayment } from "@/lib/production-workflow";

export type FinanceSettings = { id:string; usd_to_cad:number; stripe_fee_percent:number; stripe_fee_fixed_cents:number; updated_at:string; updated_by:string };
export type FinanceExpense = { id:string; expense_date:string; category:string; description:string; vendor:string|null; amount_cents:number; currency:"usd"|"cad"; usd_to_cad:number|null; status:"recorded"|"void"; receipt_reference:string|null; created_at:string; created_by:string; updated_at:string };
export type FinanceTransaction = { id:string; source:"Consultation"|"Dossier"; reference:string; client:string; paidAt:string; grossUsd:number; feeUsd:number; netUsd:number; grossCad:number; netCad:number; refundedUsd:number; settlementCurrency:string; exchangeRate:number|null; feeEstimated:boolean; test:boolean };

function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase finances manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label}: ${await response.text()}`);return response;}
async function rows<T>(table:string,query:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/${table}?${query}`,{headers:headers(),cache:"no-store"}),`Lecture ${table}`);return await response.json() as T[];}

export async function getFinanceSettings(){return (await rows<FinanceSettings>("finance_settings","id=eq.default&select=*&limit=1"))[0];}
export const listFinanceExpenses=()=>rows<FinanceExpense>("finance_expenses","select=*&order=expense_date.desc,created_at.desc");
export async function updateFinanceSettings(input:{usdToCad:number;feePercent:number;fixedFeeCents:number;updatedBy:string}){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/finance_settings?id=eq.default`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({usd_to_cad:input.usdToCad,stripe_fee_percent:input.feePercent,stripe_fee_fixed_cents:input.fixedFeeCents,updated_by:input.updatedBy})}),"Mise à jour des paramètres financiers");return (await response.json() as FinanceSettings[])[0];}
export async function createFinanceExpense(input:{date:string;category:string;description:string;vendor?:string;amountCents:number;currency:"usd"|"cad";usdToCad:number;receiptReference?:string;createdBy:string}){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/finance_expenses`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({expense_date:input.date,category:input.category,description:input.description,vendor:input.vendor||null,amount_cents:input.amountCents,currency:input.currency,usd_to_cad:input.usdToCad,receipt_reference:input.receiptReference||null,created_by:input.createdBy})}),"Création de la dépense");return (await response.json() as FinanceExpense[])[0];}
export async function voidFinanceExpense(id:string){const{url}=config();await checked(await fetch(`${url}/rest/v1/finance_expenses?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status:"void"})}),"Annulation de la dépense");}

export function buildFinancialDashboard(input:{appointments:Appointment[];payments:ClientPayment[];expenses:FinanceExpense[];settings:FinanceSettings;now?:Date}){
  const {settings}=input; const rate=Number(settings.usd_to_cad); const appointmentSessions=new Set(input.appointments.map(item=>item.stripe_session_id));
  const fee=(grossCents:number,actual?:number|null)=>actual==null?Math.round(grossCents*Number(settings.stripe_fee_percent)/100)+Number(settings.stripe_fee_fixed_cents):actual;
  const appointmentTransactions:FinanceTransaction[]=input.appointments.map(item=>{const gross=item.amount_cents;const settledGross=item.stripe_settlement_gross_cents;const settledFee=item.stripe_settlement_fee_cents;const settledNet=item.stripe_settlement_net_cents;const settlementCurrency=(item.stripe_settlement_currency||"USD").toUpperCase();const actual=item.stripe_fee_cents;const feeCents=fee(gross,actual);const converted=settlementCurrency==="CAD"&&settledGross!=null;return{id:item.id,source:"Consultation",reference:item.invoice_number,client:item.client_full_name,paidAt:item.confirmed_at||item.created_at,grossUsd:gross/100,feeUsd:converted&&settledFee!=null?settledFee/100/rate:feeCents/100,netUsd:converted&&settledNet!=null?settledNet/100/rate:(gross-feeCents)/100,grossCad:converted?settledGross/100:gross/100*rate,netCad:converted&&settledNet!=null?settledNet/100:(gross-feeCents)/100*rate,refundedUsd:(item.stripe_refunded_cents||0)/100,settlementCurrency,exchangeRate:item.stripe_exchange_rate||null,feeEstimated:settledFee==null,test:item.stripe_session_id.startsWith("cs_test_")};});
  const dossierTransactions:FinanceTransaction[]=input.payments.filter(item=>item.status==="paid"&&!appointmentSessions.has(item.stripe_session_id||"")).map(item=>{const gross=item.amount_cents;const actual=(item as ClientPayment&{stripe_fee_cents?:number|null}).stripe_fee_cents;const feeCents=fee(gross,actual);return{id:item.id,source:"Dossier",reference:item.stripe_session_id||item.id,client:item.description,paidAt:item.paid_at||item.created_at,grossUsd:gross/100,feeUsd:feeCents/100,netUsd:(gross-feeCents)/100,grossCad:gross/100*rate,netCad:(gross-feeCents)/100*rate,refundedUsd:0,settlementCurrency:"CAD",exchangeRate:null,feeEstimated:actual==null,test:Boolean(item.stripe_session_id?.startsWith("cs_test_"))};});
  const transactions=[...appointmentTransactions,...dossierTransactions].sort((a,b)=>Date.parse(b.paidAt)-Date.parse(a.paidAt));
  const expensesCad=input.expenses.filter(item=>item.status==="recorded").reduce((sum,item)=>sum+item.amount_cents/100*(item.currency==="usd"?Number(item.usd_to_cad||rate):1),0);
  const totals=transactions.reduce((acc,item)=>({grossUsd:acc.grossUsd+item.grossUsd,feesUsd:acc.feesUsd+item.feeUsd,netUsd:acc.netUsd+item.netUsd,grossCad:acc.grossCad+item.grossCad,netCad:acc.netCad+item.netCad,refundedUsd:acc.refundedUsd+item.refundedUsd}),{grossUsd:0,feesUsd:0,netUsd:0,grossCad:0,netCad:0,refundedUsd:0});
  const months=Array.from({length:12},(_,index)=>{const now=input.now||new Date();const date=new Date(now.getFullYear(),now.getMonth()-11+index,1);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;const monthly=transactions.filter(item=>item.paidAt.slice(0,7)===key);const monthlyExpenses=input.expenses.filter(item=>item.status==="recorded"&&item.expense_date.slice(0,7)===key).reduce((sum,item)=>sum+item.amount_cents/100*(item.currency==="usd"?Number(item.usd_to_cad||rate):1),0);return{key,label:date.toLocaleDateString("fr-CA",{month:"short"}),revenueCad:monthly.reduce((sum,item)=>sum+item.netCad,0),expensesCad:monthlyExpenses};});
  return{transactions,expenses:input.expenses,settings,months,totals:{...totals,expensesCad,operatingNetCad:totals.netCad-expensesCad,pendingUsd:input.payments.filter(item=>item.status==="pending").reduce((sum,item)=>sum+item.amount_cents/100,0),testTransactions:transactions.filter(item=>item.test).length}};
}
