import "server-only";

export type JulieWorkingMemory={activeClientId?:string;activeClientName?:string;currentObjective?:string;lastUserRequest?:string;lastAnswer?:string;lastActions?:Array<{tool:string;status:string;label:string;clientId?:string}>;pendingApprovalIds?:string[];generatedDocumentIds?:string[];updatedAt?:string};
export type JulieActionRun={id:string;status:"pending"|"awaiting_approval"|"executing"|"completed"|"failed"|"cancelled";output:Record<string,unknown>|null;error:string|null;attempt_count:number};

function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante pour le moteur Julie.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label} (${response.status}) : ${await response.text()}`);return response;}

export async function updateJulieWorkingMemory(conversationId:string,patch:JulieWorkingMemory){const{url}=config();const current=await checked(await fetch(`${url}/rest/v1/julie_conversations?id=eq.${encodeURIComponent(conversationId)}&select=working_memory&limit=1`,{headers:headers(),cache:"no-store"}),"Lecture mémoire Julie").then(response=>response.json() as Promise<Array<{working_memory?:JulieWorkingMemory}>>);const memory={...(current[0]?.working_memory||{}),...patch,updatedAt:new Date().toISOString()};await checked(await fetch(`${url}/rest/v1/julie_conversations?id=eq.${encodeURIComponent(conversationId)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({working_memory:memory,last_completed_action_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Mise à jour mémoire Julie");return memory;}

export async function createJulieGoal(input:{conversationId:string;clientId?:string;objective:string;plan:unknown[];status:"planning"|"awaiting_approval"|"executing"}){const{url}=config();const rows=await checked(await fetch(`${url}/rest/v1/julie_goal_runs`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({conversation_id:input.conversationId,client_id:input.clientId||null,objective:input.objective.slice(0,30000),plan:input.plan,status:input.status})}),"Création objectif Julie").then(response=>response.json() as Promise<Array<{id:string}>>);return rows[0];}

export async function finishJulieGoal(id:string,status:"completed"|"failed",result?:unknown,error?:string){const{url}=config();await checked(await fetch(`${url}/rest/v1/julie_goal_runs?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status,result:result&&typeof result==="object"?result:null,error:error||null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Finalisation objectif Julie");}

export async function beginJulieAction(input:{conversationId:string;goalRunId?:string;approvalId?:string;idempotencyKey:string;actionIndex:number;tool:string;payload:unknown}){const{url}=config();const existing=await checked(await fetch(`${url}/rest/v1/julie_action_runs?idempotency_key=eq.${encodeURIComponent(input.idempotencyKey)}&select=*&limit=1`,{headers:headers(),cache:"no-store"}),"Recherche exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);if(existing[0]?.status==="completed")return{run:existing[0],alreadyCompleted:true};const now=new Date().toISOString();if(existing[0]){const rows=await checked(await fetch(`${url}/rest/v1/julie_action_runs?id=eq.${existing[0].id}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({status:"executing",attempt_count:existing[0].attempt_count+1,error:null,started_at:now,updated_at:now})}),"Reprise exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);return{run:rows[0],alreadyCompleted:false};}const rows=await checked(await fetch(`${url}/rest/v1/julie_action_runs`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({goal_run_id:input.goalRunId||null,conversation_id:input.conversationId,approval_id:input.approvalId||null,idempotency_key:input.idempotencyKey,action_index:input.actionIndex,tool:input.tool,input:input.payload,status:"executing",attempt_count:1,started_at:now})}),"Démarrage exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);return{run:rows[0],alreadyCompleted:false};}

export async function finishJulieAction(id:string,status:"completed"|"failed",output?:unknown,error?:string){const{url}=config();await checked(await fetch(`${url}/rest/v1/julie_action_runs?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status,output:output&&typeof output==="object"?output:null,error:error||null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Finalisation exécution Julie");}
