import "server-only";

export type JulieWorkingMemory={activeClientId?:string;activeClientName?:string;currentObjective?:string;lastUserRequest?:string;lastAnswer?:string;lastActions?:Array<{tool:string;status:string;label:string;clientId?:string}>;pendingApprovalIds?:string[];generatedDocumentIds?:string[];updatedAt?:string};
export type JulieActionRun={id:string;status:"pending"|"awaiting_approval"|"executing"|"completed"|"failed"|"cancelled";output:Record<string,unknown>|null;error:string|null;attempt_count:number};
export type JulieGlobalMemory={id:string;client_id:string|null;memory_type:string;content:string;metadata:Record<string,unknown>;importance:number;updated_at:string};
export type JulieRuntimeState={goals:Array<{id:string;objective:string;status:string;client_id:string|null;created_at:string;updated_at:string}>;actions:Array<{id:string;goal_run_id:string|null;tool:string;status:string;action_index:number;error:string|null;updated_at:string}>};

function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante pour le moteur Julie.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label} (${response.status}) : ${await response.text()}`);return response;}

export async function updateJulieWorkingMemory(conversationId:string,patch:JulieWorkingMemory){const{url}=config();const current=await checked(await fetch(`${url}/rest/v1/julie_conversations?id=eq.${encodeURIComponent(conversationId)}&select=working_memory&limit=1`,{headers:headers(),cache:"no-store"}),"Lecture mémoire Julie").then(response=>response.json() as Promise<Array<{working_memory?:JulieWorkingMemory}>>);const memory={...(current[0]?.working_memory||{}),...patch,updatedAt:new Date().toISOString()};await checked(await fetch(`${url}/rest/v1/julie_conversations?id=eq.${encodeURIComponent(conversationId)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({working_memory:memory,last_completed_action_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Mise à jour mémoire Julie");return memory;}

export async function createJulieGoal(input:{conversationId:string;clientId?:string;objective:string;plan:unknown[];status:"planning"|"awaiting_approval"|"executing"}){const{url}=config();const rows=await checked(await fetch(`${url}/rest/v1/julie_goal_runs`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({conversation_id:input.conversationId,client_id:input.clientId||null,objective:input.objective.slice(0,30000),plan:input.plan,status:input.status})}),"Création objectif Julie").then(response=>response.json() as Promise<Array<{id:string}>>);return rows[0];}

export async function seedJulieGoalActions(input:{goalRunId:string;conversationId:string;actions:Array<{tool:string;arguments?:Record<string,unknown>;clientQuery?:string}>}){if(!input.actions.length)return[];const{url}=config();const rows=input.actions.map((action,index)=>({goal_run_id:input.goalRunId,conversation_id:input.conversationId,idempotency_key:`goal:${input.goalRunId}:action:${index}`,action_index:index,tool:action.tool,input:action,status:"pending",attempt_count:0}));return checked(await fetch(`${url}/rest/v1/julie_action_runs?on_conflict=idempotency_key`,{method:"POST",headers:headers("resolution=ignore-duplicates,return=representation"),body:JSON.stringify(rows)}),"Création étapes Julie").then(response=>response.json() as Promise<JulieActionRun[]>);}

export async function setJulieActionStatus(goalRunId:string,actionIndex:number,status:"pending"|"awaiting_approval"|"executing"|"completed"|"failed",approvalId?:string){const{url}=config();const now=new Date().toISOString();await checked(await fetch(`${url}/rest/v1/julie_action_runs?goal_run_id=eq.${encodeURIComponent(goalRunId)}&action_index=eq.${actionIndex}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status,approval_id:approvalId||undefined,updated_at:now,...(status==="executing"?{started_at:now}:{})})}),"Mise à jour étape Julie");}

export async function finishJulieGoal(id:string,status:"completed"|"failed",result?:unknown,error?:string){const{url}=config();await checked(await fetch(`${url}/rest/v1/julie_goal_runs?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status,result:result&&typeof result==="object"?result:null,error:error||null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Finalisation objectif Julie");}

export async function beginJulieAction(input:{conversationId:string;goalRunId?:string;approvalId?:string;idempotencyKey:string;actionIndex:number;tool:string;payload:unknown}){const{url}=config();const existing=await checked(await fetch(`${url}/rest/v1/julie_action_runs?idempotency_key=eq.${encodeURIComponent(input.idempotencyKey)}&select=*&limit=1`,{headers:headers(),cache:"no-store"}),"Recherche exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);if(existing[0]?.status==="completed")return{run:existing[0],alreadyCompleted:true};const now=new Date().toISOString();if(existing[0]){const rows=await checked(await fetch(`${url}/rest/v1/julie_action_runs?id=eq.${existing[0].id}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({status:"executing",attempt_count:existing[0].attempt_count+1,error:null,started_at:now,updated_at:now})}),"Reprise exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);return{run:rows[0],alreadyCompleted:false};}const rows=await checked(await fetch(`${url}/rest/v1/julie_action_runs`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({goal_run_id:input.goalRunId||null,conversation_id:input.conversationId,approval_id:input.approvalId||null,idempotency_key:input.idempotencyKey,action_index:input.actionIndex,tool:input.tool,input:input.payload,status:"executing",attempt_count:1,started_at:now})}),"Démarrage exécution Julie").then(response=>response.json() as Promise<JulieActionRun[]>);return{run:rows[0],alreadyCompleted:false};}

export async function finishJulieAction(id:string,status:"completed"|"failed",output?:unknown,error?:string){const{url}=config();await checked(await fetch(`${url}/rest/v1/julie_action_runs?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({status,output:output&&typeof output==="object"?output:null,error:error||null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()})}),"Finalisation exécution Julie");}

export async function listJulieGlobalMemory(clientId?:string){const{url}=config();const filter=clientId?`or=(client_id.eq.${encodeURIComponent(clientId)},client_id.is.null)&`:"client_id=is.null&";return checked(await fetch(`${url}/rest/v1/julie_global_memories?${filter}select=*&order=importance.desc,updated_at.desc&limit=40`,{headers:headers(),cache:"no-store"}),"Lecture mémoire globale Julie").then(response=>response.json() as Promise<JulieGlobalMemory[]>);}

export async function rememberJulieOutcome(input:{conversationId:string;clientId?:string;instruction:string;answer:string;actions?:Array<{tool:string;status:string;label:string}>}){const{url}=config();const normalized=`${input.clientId||"global"}:${input.instruction.toLocaleLowerCase("fr-CA").replace(/\s+/g," ").trim().slice(0,180)}`,dedupeKey=Buffer.from(normalized).toString("base64url").slice(0,240);const content=`Demande : ${input.instruction}\nRésultat : ${input.answer}`.slice(0,12000);await checked(await fetch(`${url}/rest/v1/julie_global_memories?on_conflict=dedupe_key`,{method:"POST",headers:headers("resolution=merge-duplicates,return=minimal"),body:JSON.stringify({client_id:input.clientId||null,conversation_id:input.conversationId,memory_type:"action",dedupe_key:dedupeKey,content,metadata:{actions:input.actions||[]},importance:input.actions?.some(action=>action.status==="failed")?8:6,updated_at:new Date().toISOString()})}),"Enregistrement mémoire globale Julie");}

export async function getJulieRuntimeState(conversationId:string):Promise<JulieRuntimeState>{const{url}=config();const goals=await checked(await fetch(`${url}/rest/v1/julie_goal_runs?conversation_id=eq.${encodeURIComponent(conversationId)}&select=id,objective,status,client_id,created_at,updated_at&order=created_at.desc&limit=10`,{headers:headers(),cache:"no-store"}),"Lecture missions Julie").then(response=>response.json() as Promise<JulieRuntimeState["goals"]>);const goalIds=goals.map(goal=>goal.id);const actions=goalIds.length?await checked(await fetch(`${url}/rest/v1/julie_action_runs?goal_run_id=in.(${goalIds.join(",")})&select=id,goal_run_id,tool,status,action_index,error,updated_at&order=created_at.desc&limit=100`,{headers:headers(),cache:"no-store"}),"Lecture étapes Julie").then(response=>response.json() as Promise<JulieRuntimeState["actions"]>):[];return{goals,actions};}
