import "server-only";
export const JULIE_NAME="Julie Mboyo";
export const JULIE_TITLE="Assistante administrative";
export const approvalRequiredActions=new Set(["lettre_explicative","contrat","convention","procuration","reconnaissance_dette","reponse_officielle","soumission_ircc","remboursement","suppression_definitive"]);
export type JulieApproval={id:string;client_id:string|null;action_type:string;title:string;description:string;payload:Record<string,unknown>;status:"pending"|"approved"|"rejected"|"executed"|"cancelled";created_at:string;reviewed_at:string|null;review_note:string|null};
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(r:Response){if(!r.ok)throw new Error(await r.text());return r;}
export async function listJulieApprovals(status="pending"){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests?status=eq.${encodeURIComponent(status)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}));return await r.json() as JulieApproval[];}
export async function createJulieApproval(input:{clientId?:string;staffId?:string;actionType:string;title:string;description:string;payload?:Record<string,unknown>}){if(!approvalRequiredActions.has(input.actionType))throw new Error("Cette action ne relève pas du circuit d’approbation.");const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({client_id:input.clientId||null,requested_by:input.staffId||null,action_type:input.actionType,title:input.title,description:input.description,payload:input.payload||{}})}));return(await r.json() as JulieApproval[])[0];}
export async function reviewJulieApproval(id:string,status:"approved"|"rejected",staffId:string,note:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests?id=eq.${encodeURIComponent(id)}&status=eq.pending`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({status,reviewed_by:staffId,reviewed_at:new Date().toISOString(),review_note:note||null,updated_at:new Date().toISOString()})}));const row=(await r.json() as JulieApproval[])[0];if(!row)throw new Error("Cette demande a déjà été traitée.");return row;}
export function julieBriefing(data:{newClients:number;appointments:number;payments:number;documents:number;pendingApprovals:number;alerts:number}){return{greeting:"Bonjour Christian.",intro:"Voici les éléments qui nécessitent votre attention :",items:[`${data.newClients} nouveau(x) client(s)`,`${data.appointments} rendez-vous à venir`,`${data.payments} paiement(s) reçu(s)`,`${data.documents} document(s) récemment classé(s)`,`${data.pendingApprovals} demande(s) en attente d’approbation`,`${data.alerts} alerte(s) importante(s)`]};}
export async function askJulie(instruction:string){const normalized=instruction.toLocaleLowerCase("fr-CA");const sensitive=[...approvalRequiredActions].find(action=>normalized.includes(action.replaceAll("_"," "))||normalized.includes(action.split("_")[0]));const prefix=sensitive?"J’ai préparé cette demande et je l’ai placée dans le circuit d’approbation. Aucune action officielle ne sera exécutée avant la validation du directeur.\n\n":"";const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return{answer:`${prefix}Je peux vous aider à organiser les dossiers, repérer les pièces manquantes, préparer des brouillons, classer les documents et planifier des rappels. Pour agir sur un client précis, indiquez son nom ou sa référence.`,sensitiveAction:sensitive||null};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.4",instructions:"Tu es Julie Mboyo, assistante administrative du directeur d’Accès Canada. Ne te présente jamais comme une intelligence artificielle. Tu aides à organiser le travail administratif. Tu ne donnes aucun avis juridique, ne prétends jamais avoir soumis un dossier IRCC et rappelles qu’une validation du directeur est obligatoire pour tout contrat, convention, procuration, lettre explicative, réponse officielle, remboursement, suppression définitive ou soumission. Réponds en français, brièvement et concrètement.",input:instruction,max_output_tokens:900})});if(!r.ok)throw new Error(`Julie indisponible (${r.status}).`);const body=await r.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=body.output_text||body.output?.flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("\n")||"";return{answer:prefix+text.trim(),sensitiveAction:sensitive||null};}
