import "server-only";
export const JULIE_NAME="Julie Mboyo"; export const JULIE_TITLE="Assistante administrative";
export const approvalRequiredActions=new Set(["lettre_explicative","contrat","convention","procuration","reconnaissance_dette","reponse_officielle","soumission_ircc","envoi_document_officiel","signature_electronique","remboursement","suppression_definitive","modification_facture"]);
export type JulieApproval={id:string;client_id:string|null;action_type:string;title:string;description:string;payload:Record<string,unknown>;status:"pending"|"approved"|"rejected"|"executed"|"cancelled";created_at:string;reviewed_at:string|null;review_note:string|null};
export type JulieMessage={id:string;conversation_id:string;role:"staff"|"julie"|"system";content:string;created_at:string};
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(r:Response){if(!r.ok)throw new Error(await r.text());return r;}
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function nullableStaffId(value?:string){return value&&uuidPattern.test(value)?value:null;}
export async function listJulieApprovals(status="pending"){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests?status=eq.${encodeURIComponent(status)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}));return await r.json() as JulieApproval[];}
export async function createJulieApproval(input:{clientId?:string;staffId?:string;actionType:string;title:string;description:string;payload?:Record<string,unknown>}){if(!approvalRequiredActions.has(input.actionType))throw new Error("Cette action ne relève pas du circuit d’approbation.");const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({client_id:input.clientId||null,requested_by:nullableStaffId(input.staffId),action_type:input.actionType,title:input.title,description:input.description,payload:input.payload||{}})}));return(await r.json() as JulieApproval[])[0];}
export async function reviewJulieApproval(id:string,status:"approved"|"rejected",staffId:string,note:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_approval_requests?id=eq.${encodeURIComponent(id)}&status=eq.pending`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({status,reviewed_by:nullableStaffId(staffId),reviewed_at:new Date().toISOString(),review_note:note||null,updated_at:new Date().toISOString()})}));const row=(await r.json() as JulieApproval[])[0];if(!row)throw new Error("Cette demande a déjà été traitée.");return row;}
export async function getJulieConversation(staffId:string){const{url}=config();const safeStaffId=nullableStaffId(staffId);const staffFilter=safeStaffId?`staff_id=eq.${encodeURIComponent(safeStaffId)}`:"staff_id=is.null";let r=await checked(await fetch(`${url}/rest/v1/julie_conversations?${staffFilter}&status=eq.active&select=*&order=updated_at.desc&limit=1`,{headers:headers(),cache:"no-store"}));const rows=await r.json() as {id:string}[];if(rows[0])return rows[0];r=await checked(await fetch(`${url}/rest/v1/julie_conversations`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({staff_id:safeStaffId,title:"Conversation avec Julie"})}));return(await r.json() as {id:string}[])[0];}
export async function listJulieMessages(conversationId:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_messages?conversation_id=eq.${encodeURIComponent(conversationId)}&select=*&order=created_at.asc&limit=200`,{headers:headers(),cache:"no-store"}));return await r.json() as JulieMessage[];}
export async function saveJulieMessage(conversationId:string,role:JulieMessage["role"],content:string){const{url}=config();const r=await checked(await fetch(`${url}/rest/v1/julie_messages`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify({conversation_id:conversationId,role,content:content.slice(0,30000)})}));await fetch(`${url}/rest/v1/julie_conversations?id=eq.${conversationId}`,{method:"PATCH",headers:headers(),body:JSON.stringify({updated_at:new Date().toISOString()})});return(await r.json() as JulieMessage[])[0];}
export async function setJulieConversationClient(conversationId:string,clientId?:string){if(!clientId)return;const{url}=config();await checked(await fetch(`${url}/rest/v1/julie_conversations?id=eq.${encodeURIComponent(conversationId)}`,{method:"PATCH",headers:headers(),body:JSON.stringify({client_id:clientId,updated_at:new Date().toISOString()})}));}
export function julieBriefing(data:{newClients:number;appointments:number;payments:number;documents:number;pendingApprovals:number;alerts:number}){return{greeting:"Bonjour Christian.",intro:"Voici les éléments qui nécessitent votre attention :",items:[`${data.newClients} nouveau(x) client(s)`,`${data.appointments} rendez-vous à venir`,`${data.payments} paiement(s) reçu(s)`,`${data.documents} document(s) récemment classé(s)`,`${data.pendingApprovals} demande(s) en attente d’approbation`,`${data.alerts} alerte(s) importante(s)`]};}
export async function getJulieDashboardBriefing(staffId:string){const{url}=config();const safeStaffId=nullableStaffId(staffId);const staff=safeStaffId?await checked(await fetch(`${url}/rest/v1/staff_members?id=eq.${encodeURIComponent(safeStaffId)}&select=previous_login_at&limit=1`,{headers:headers(),cache:"no-store"})).then(r=>r.json() as Promise<Array<{previous_login_at:string|null}>>):[];const since=staff[0]?.previous_login_at||new Date(Date.now()-86400000).toISOString();async function count(table:string,extra=""){const r=await checked(await fetch(`${url}/rest/v1/${table}?created_at=gte.${encodeURIComponent(since)}${extra}&select=id`,{headers:headers(),cache:"no-store"}));return(await r.json() as unknown[]).length;}const[newClients,appointments,payments,documents,pendingApprovals,alerts]=await Promise.all([count("admin_clients"),count("client_appointments"),count("client_payments","&status=eq.paid"),count("client_uploaded_documents"),count("julie_approval_requests","&status=eq.pending"),count("admin_notifications","&severity=in.(warning,urgent)&status=eq.unread")]);return{since,...julieBriefing({newClients,appointments,payments,documents,pendingApprovals,alerts})};}
export async function askJulie(instruction:string,history:JulieMessage[]=[]){const normalized=instruction.toLocaleLowerCase("fr-CA");const sensitive=[...approvalRequiredActions].find(action=>normalized.includes(action.replaceAll("_"," "))||normalized.includes(action.split("_")[0]));const prefix=sensitive?"J’ai préparé cette demande et je l’ai placée dans le circuit d’approbation. Aucune action officielle ne sera exécutée avant la validation du directeur.\n\n":"";const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return{answer:`${prefix}Je peux organiser les dossiers, repérer les pièces manquantes, préparer des brouillons, classer les documents et planifier des rappels. Pour agir sur un client précis, indiquez son nom ou sa référence.`,sensitiveAction:sensitive||null};const context=history.slice(-30).map(m=>`${m.role==="julie"?"Julie":"Directeur"}: ${m.content}`).join("\n");const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.4",instructions:"Tu es Julie Mboyo, assistante administrative du directeur d’Accès Canada. Ne te présente jamais comme une intelligence artificielle. Tu ne donnes aucun avis juridique et ne prétends jamais avoir soumis un dossier IRCC. La validation du directeur est obligatoire pour toute action officielle ou financière.",input:`Historique:\n${context}\n\nNouvelle demande:\n${instruction}`,max_output_tokens:900})});if(!r.ok)throw new Error(`Julie indisponible (${r.status}).`);const body=await r.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=body.output_text||body.output?.flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("\n")||"";return{answer:prefix+text.trim(),sensitiveAction:sensitive||null};}
