import { questionnaireLabels, type QuestionnaireType } from "./questionnaire-definitions.ts";

function esc(value: string) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
export function questionnaireInvitationEmail({ name, type, url, expiresAt, siteUrl }: { name: string; type: QuestionnaireType; url: string; expiresAt: string; siteUrl: string }) {
  const expiry = new Date(expiresAt).toLocaleString("fr-CA", { dateStyle: "long", timeStyle: "short", timeZone: "America/Toronto" }); const title = questionnaireLabels[type]; const logo = `${siteUrl.replace(/\/$/, "")}/images/logo.png`;
  const text = `Bonjour ${name},\n\nAccès Canada vous invite à remplir le ${title.toLowerCase()}.\nLien sécurisé : ${url}\nExpiration : ${expiry}\n\nCe lien est personnel. Vous pouvez enregistrer un brouillon et reprendre plus tard.\n\nAccès Canada`;
  const html = `<!doctype html><html lang="fr"><body style="margin:0;background:#f8f6ef;font-family:Arial,sans-serif;color:#0b1d36"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 14px 40px rgba(11,29,54,.12)"><tr><td style="background:#0b1d36;padding:28px 34px;border-bottom:4px solid #d4af37"><img src="${logo}" width="72" height="72" alt="Logo Accès Canada" style="display:block;border-radius:16px;background:#fff"><h1 style="margin:18px 0 5px;color:#fff;font-size:26px">Accès Canada</h1><p style="margin:0;color:#d4af37;font-weight:bold">Votre questionnaire sécurisé</p></td></tr><tr><td style="padding:34px"><p style="font-size:17px">Bonjour <strong>${esc(name)}</strong>,</p><p style="line-height:1.7;color:#405065">Nous vous invitons à remplir le <strong>${esc(title.toLowerCase())}</strong>. Vous pouvez enregistrer un brouillon et reprendre plus tard.</p><p style="text-align:center;margin:30px 0"><a href="${esc(url)}" style="display:inline-block;background:#c8102e;color:#fff;text-decoration:none;padding:15px 26px;border-radius:999px;font-weight:bold">Remplir mon questionnaire</a></p><table role="presentation" width="100%" style="background:#f8f6ef;border-left:4px solid #d4af37;border-radius:12px"><tr><td style="padding:16px"><strong>Expiration du lien</strong><br><span style="color:#596779">${esc(expiry)}</span></td></tr></table><p style="margin-top:24px;font-size:13px;line-height:1.6;color:#657184">🔒 Ce lien personnel et non prévisible donne accès à des renseignements confidentiels. Ne le transférez pas. Une régénération par Accès Canada invalidera automatiquement le lien précédent.</p></td></tr><tr><td style="background:#0b1d36;padding:20px 34px;color:#fff;font-size:12px;text-align:center">Document et accès confidentiels · Accès Canada</td></tr></table></td></tr></table></body></html>`;
  return { text, html };
}
