import "server-only";
import { inflateSync } from "node:zlib";
import type { DocumentSignatureConfig, SignatureVector } from "./document-branding";

export type SignerKey="director"|"legal_counsel";
export type SignatureSetting={signer_key:SignerKey;display_name:string;job_title:string;enabled:boolean;storage_path:string|null;vector_data:SignatureVector|null;updated_at:string};
const defaults:SignatureSetting[]=[
  {signer_key:"director",display_name:"Christian Nkuli Mboyo",job_title:"Directeur général",enabled:true,storage_path:null,vector_data:null,updated_at:new Date(0).toISOString()},
  {signer_key:"legal_counsel",display_name:"Me Régine Sifa Buledi",job_title:"Conseillère juridique",enabled:true,storage_path:null,vector_data:null,updated_at:new Date(0).toISOString()},
];
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
export async function listSignatureSettings(){try{const{url}=config();const r=await fetch(`${url}/rest/v1/document_signature_settings?select=*&order=signer_key`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(await r.text());const rows=await r.json() as SignatureSetting[];return defaults.map(d=>rows.find(r=>r.signer_key===d.signer_key)||d);}catch{return defaults;}}
export async function getDocumentSignatureConfig():Promise<DocumentSignatureConfig>{const rows=await listSignatureSettings(),director=rows.find(r=>r.signer_key==="director"),counsel=rows.find(r=>r.signer_key==="legal_counsel");return{director:{enabled:director?.enabled!==false,vector:director?.vector_data},counsel:{enabled:counsel?.enabled!==false,vector:counsel?.vector_data}};}
export async function setSignatureEnabled(signer:SignerKey,enabled:boolean,updatedBy:string){const{url}=config();const r=await fetch(`${url}/rest/v1/document_signature_settings?signer_key=eq.${signer}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({enabled,updated_by:updatedBy,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());return (await r.json() as SignatureSetting[])[0];}
export async function uploadSignature(signer:SignerKey,file:Buffer,updatedBy:string){const vector=pngToVector(file);const{url,key}=config(),path=`${signer}.png`;const stored=await fetch(`${url}/storage/v1/object/document-signatures/${path}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"image/png",xUpsert:"true"},body:new Uint8Array(file)});if(!stored.ok)throw new Error(await stored.text());const r=await fetch(`${url}/rest/v1/document_signature_settings?signer_key=eq.${signer}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({storage_path:path,vector_data:vector,enabled:true,updated_by:updatedBy,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());return (await r.json() as SignatureSetting[])[0];}
export async function readSignaturePng(signer:SignerKey){const settings=await listSignatureSettings(),row=settings.find(r=>r.signer_key===signer);if(!row?.storage_path){if(signer==="director")return null;return null;}const{url,key}=config();const r=await fetch(`${url}/storage/v1/object/document-signatures/${row.storage_path}`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:"no-store"});if(!r.ok)return null;return Buffer.from(await r.arrayBuffer());}

function pngToVector(file:Buffer):SignatureVector{if(file.length<33||file.toString("ascii",1,4)!=="PNG")throw new Error("Le fichier doit être un PNG valide.");const width=file.readUInt32BE(16),height=file.readUInt32BE(20),depth=file[24],color=file[25],interlace=file[28];if(!width||!height||width>2400||height>1200||depth!==8||![4,6].includes(color)||interlace!==0)throw new Error("Utilisez un PNG transparent 8 bits, non entrelacé, de 2400 × 1200 px maximum.");let pos=8,idat=Buffer.alloc(0);while(pos+12<=file.length){const len=file.readUInt32BE(pos),type=file.toString("ascii",pos+4,pos+8);if(type==="IDAT")idat=Buffer.concat([idat,file.subarray(pos+8,pos+8+len)]);pos+=12+len;}const channels=color===6?4:2,stride=width*channels,raw=inflateSync(idat);if(raw.length<(stride+1)*height)throw new Error("PNG incomplet.");const pixels=Buffer.alloc(stride*height);let source=0,transparent=false,opaque=false;for(let y=0;y<height;y++){const filter=raw[source++];for(let x=0;x<stride;x++){const value=raw[source++],left=x>=channels?pixels[y*stride+x-channels]:0,up=y?pixels[(y-1)*stride+x]:0,upLeft=y&&x>=channels?pixels[(y-1)*stride+x-channels]:0;let decoded=value;if(filter===1)decoded=(value+left)&255;else if(filter===2)decoded=(value+up)&255;else if(filter===3)decoded=(value+Math.floor((left+up)/2))&255;else if(filter===4){const p=left+up-upLeft,pa=Math.abs(p-left),pb=Math.abs(p-up),pc=Math.abs(p-upLeft);decoded=(value+(pa<=pb&&pa<=pc?left:pb<=pc?up:upLeft))&255;}else if(filter!==0)throw new Error("Filtre PNG non pris en charge.");pixels[y*stride+x]=decoded;}}
const runs:Array<[number,number,number]>=[];for(let y=0;y<height;y++){let start=-1;for(let x=0;x<width;x++){const alpha=pixels[y*stride+x*channels+channels-1];transparent ||= alpha<250;opaque ||= alpha>40;const ink=alpha>40;if(ink&&start<0)start=x;if((!ink||x===width-1)&&start>=0){runs.push([start,y,(ink&&x===width-1?x+1:x)-start]);start=-1;}}}if(!transparent)throw new Error("Le PNG doit contenir un fond transparent.");if(!opaque||runs.length<5)throw new Error("Aucune signature lisible n’a été détectée.");return{width,height,runs};}
