import "server-only";

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { AlignmentType, BorderStyle, Document, Footer, Header, HeadingLevel, ImageRun, Packer, PageNumber, Paragraph, TextRun } from "docx";
import type { AdminClient } from "@/lib/admin-data";
import { createClientUpload, uploadClientFile } from "@/lib/client-portal";
import { assertMonthlyAiBudget, recordAiUsage } from "@/lib/ai-usage";
import { BrandedPdfBuilder, pdfLine, pdfRect, pdfText, premiumFooterCommands } from "@/lib/document-branding";
import { brand } from "@/lib/site";

export type SmartDocumentKind = "contrat"|"lettre"|"formulaire"|"questionnaire"|"checklist"|"procedure"|"modele"|"autre";
export type SmartDocument = { id:string;client_id:string;parent_document_id:string|null;title:string;category:string;document_kind:SmartDocumentKind;source_text:string;professional_text:string;edit_instruction:string|null;version:number;word_upload_id:string|null;pdf_upload_id:string|null;model:string|null;created_by:string;created_at:string };

function crmCategory(value:string){const text=value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase();if(text.includes("garant"))return "garant_financier";if(text.includes("formulaire"))return "formulaires_ircc";if(text.includes("financ"))return "situation_financiere";if(text.includes("emploi")||text.includes("contrat"))return "emploi_commerce";if(text.includes("lettre")||text.includes("correspond"))return "correspondance";return "acces_canada";}
function slug(value:string){return value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)||"document";}
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante pour les documents intelligents.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label} (${response.status}) : ${await response.text()}`);return response;}

export async function getSmartDocument(id:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,{headers:headers(),cache:"no-store"}),"Lecture document intelligent");return((await response.json()) as SmartDocument[])[0]||null;}
export async function listSmartDocuments(clientId:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?client_id=eq.${encodeURIComponent(clientId)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}),"Liste documents intelligents");return await response.json() as SmartDocument[];}

async function improveText(input:{source:string;instruction?:string;kind:SmartDocumentKind;title:string;client:AdminClient}){
  const token=process.env.OPENAI_API_KEY;if(!token)throw new Error("OPENAI_API_KEY n’est pas configurée.");
  await assertMonthlyAiBudget();const model=process.env.OPENAI_MODEL||"gpt-5.4";
  const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(60000),body:JSON.stringify({model,max_completion_tokens:5000,response_format:{type:"json_schema",json_schema:{name:"document_professionnel",strict:true,schema:{type:"object",additionalProperties:false,properties:{content:{type:"string"},work_summary:{type:"string"},client_actions:{type:"array",items:{type:"string"}}},required:["content","work_summary","client_actions"]}}},messages:[{role:"system",content:`Tu es Julie, rédactrice administrative principale d’Accès Canada. Tu dois TRANSFORMER réellement le brouillon, jamais recopier la demande de l’utilisateur dans le document.\n\nTravail obligatoire : corriger toutes les fautes; réécrire les phrases faibles; supprimer les répétitions; structurer le fond avec un titre, des sections et des listes; compléter uniquement par des formulations administratives génériques qui ne créent aucun fait; conserver entre crochets toute donnée manquante; adapter le registre au type de document; produire un texte directement publiable par un cabinet de consultants.\n\nInterdictions : inventer une identité, date, somme, règle juridique, décision IRCC ou promesse; inclure des commentaires sur ton travail dans le champ content; reprendre les mots « voici », « corrige », « génère », « classe » ou les instructions techniques de l’utilisateur.\n\nLe champ content contient uniquement le document final. work_summary explique brièvement les améliorations. client_actions contient les actions concrètes attendues du destinataire.`},{role:"user",content:`TYPE DE DOCUMENT: ${input.kind}\nTITRE: ${input.title}\nCLIENT: ${input.client.full_name}\nRÉFÉRENCE: ${input.client.file_reference||"[À ATTRIBUER]"}\nOBJECTIF: ${input.instruction||"Créer une version professionnelle fidèle et complète"}\n\nBROUILLON À TRANSFORMER:\n${input.source.slice(0,30000)}`}]}),});
  if(!response.ok){const detail=(await response.text()).slice(0,500);await recordAiUsage({clientId:input.client.id,feature:"smart_document",model,status:response.status===429?"quota_exceeded":"failed",errorCode:`HTTP_${response.status}`}).catch(()=>undefined);throw new Error(`Amélioration IA impossible (${response.status}) : ${detail}`);}
  const body=await response.json() as {choices?:Array<{message?:{content?:string}}>;usage?:{prompt_tokens?:number;completion_tokens?:number}};const raw=body.choices?.[0]?.message?.content?.trim();if(!raw)throw new Error("L’IA n’a produit aucun contenu.");let parsed:{content?:string;work_summary?:string;client_actions?:string[]};try{parsed=JSON.parse(raw);}catch{throw new Error("La réponse IA n’est pas un document structuré valide.");}const text=parsed.content?.trim();if(!text||text.length<80)throw new Error("Le document professionnel produit est vide ou trop court.");const sourceNorm=input.source.replace(/\s+/g," ").trim().toLowerCase(),textNorm=text.replace(/\s+/g," ").trim().toLowerCase();if(sourceNorm.length>160&&sourceNorm===textNorm)throw new Error("Julie n’a pas suffisamment transformé le brouillon. Relancez avec une instruction plus précise.");await recordAiUsage({clientId:input.client.id,feature:"smart_document",model,inputTokens:body.usage?.prompt_tokens,outputTokens:body.usage?.completion_tokens}).catch(()=>undefined);return{text,model,summary:parsed.work_summary||"Document corrigé et professionnalisé.",actions:parsed.client_actions||[]};
}

function paragraphs(text:string){return text.replace(/\r/g,"").split(/\n{2,}/).map(value=>value.trim()).filter(Boolean);}
function plainMarkdown(value:string){return value.replace(/^#{1,6}\s+/gm,"").replace(/\*\*(.*?)\*\*/g,"$1").replace(/__(.*?)__/g,"$1").replace(/^\s*[-*+]\s+/gm,"• ").replace(/`([^`]+)`/g,"$1").trim();}
function richRuns(value:string,options:{color:string;size:number;bold?:boolean}){const runs:TextRun[]=[];let cursor=0;const expression=/\*\*(.+?)\*\*|__(.+?)__/g;for(const match of value.matchAll(expression)){const index=match.index||0;if(index>cursor)runs.push(new TextRun({text:value.slice(cursor,index),color:options.color,size:options.size,bold:options.bold}));runs.push(new TextRun({text:match[1]||match[2],color:options.color,size:options.size,bold:true}));cursor=index+match[0].length;}if(cursor<value.length)runs.push(new TextRun({text:value.slice(cursor),color:options.color,size:options.size,bold:options.bold}));return runs.length?runs:[new TextRun({text:value,color:options.color,size:options.size,bold:options.bold})];}
export async function generateProfessionalDocx(client:AdminClient,title:string,content:string,version:number){
  let logo:Buffer|undefined;try{logo=await readFile(join(process.cwd(),"public","images","logo.png"));}catch{logo=undefined;}
  const navy="0B1D36",gold="D4AF37",red="C8102E";
  const headerChildren=[new Paragraph({alignment:AlignmentType.LEFT,border:{bottom:{color:gold,style:BorderStyle.SINGLE,size:16}},children:[...(logo?[new ImageRun({data:logo,transformation:{width:54,height:54},type:"png"})]:[]),new TextRun({text:"  ACCÈS CANADA",bold:true,color:navy,size:28})]})];
  const body=[new Paragraph({heading:HeadingLevel.TITLE,spacing:{before:360,after:120},children:[new TextRun({text:plainMarkdown(title),bold:true,color:navy,size:38})]}),new Paragraph({border:{bottom:{color:gold,style:BorderStyle.SINGLE,size:18}},spacing:{after:300},children:[new TextRun({text:`Préparé pour ${client.full_name}  ·  ${client.file_reference||"Référence à attribuer"}  ·  Version ${version}`,color:"667085",size:18})]}),...paragraphs(content).flatMap((block,index)=>{const lines=block.split("\n").map(v=>v.trim()).filter(Boolean);return lines.map((line,lineIndex)=>{const bullet=/^[-*•]\s+/.test(line),numbered=/^\d+[.)]\s+/.test(line),heading=!bullet&&!numbered&&line.length<90&&(/^(?:#{1,6}\s+|\*\*.+\*\*$)/.test(line)||(lineIndex===0&&lines.length===1&&index>0));const text=plainMarkdown(line.replace(/^\d+[.)]\s+/,""));return new Paragraph({heading:heading?HeadingLevel.HEADING_1:undefined,bullet:bullet?{level:0}:undefined,numbering:numbered?{reference:"ac-numbering",level:0}:undefined,keepNext:heading,spacing:{before:heading?220:0,after:heading?100:100,line:300},children:richRuns(text,{bold:heading,color:heading?navy:"172033",size:heading?26:22})});});})];
  const document=new Document({creator:"Julie · Accès Canada",title,description:`Document officiel Accès Canada pour ${client.full_name}`,numbering:{config:[{reference:"ac-numbering",levels:[{level:0,format:"decimal",text:"%1.",alignment:AlignmentType.START,style:{paragraph:{indent:{left:720,hanging:360}}}}]}]},styles:{default:{document:{run:{font:"Aptos",size:22,color:"172033"},paragraph:{spacing:{line:300,after:120}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",run:{font:"Aptos Display",size:38,bold:true,color:navy}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Aptos Display",size:26,bold:true,color:navy},paragraph:{spacing:{before:220,after:100}}}]},sections:[{properties:{page:{margin:{top:1080,right:1080,bottom:1080,left:1080},pageNumbers:{start:1}}},headers:{default:new Header({children:headerChildren})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,border:{top:{color:gold,style:BorderStyle.SINGLE,size:8}},children:[new TextRun({text:`${brand.phone} · ${brand.email} · Document confidentiel · Page `,color:"667085",size:16}),new TextRun({children:[PageNumber.CURRENT],bold:true,color:red,size:16})]})]})},children:body}]});
  return Buffer.from(await Packer.toBuffer(document));
}

function wrap(text:string,max=92){const words=text.replace(/\s+/g," ").trim().split(" "),lines:string[]=[];let line="";for(const word of words){if(`${line} ${word}`.trim().length>max&&line){lines.push(line);line=word;}else line=`${line} ${word}`.trim();}if(line)lines.push(line);return lines;}
export function generateProfessionalPdf(client:AdminClient,title:string,content:string,version:number){
  type Line={text:string;kind:"heading"|"body"|"bullet"|"space"};const builder=new BrandedPdfBuilder(),all:Line[]=[];
  for(const block of paragraphs(content)){const rawLines=block.split("\n").map(value=>value.trim()).filter(Boolean);for(const raw of rawLines){const bullet=/^[-*•]\s+/.test(raw),numbered=/^\d+[.)]\s+/.test(raw),heading=!bullet&&!numbered&&raw.length<90&&/^(?:#{1,6}\s+|\*\*.+\*\*$)/.test(raw),clean=plainMarkdown(raw.replace(/^\d+[.)]\s+/,"")),prefix=bullet?"- ":numbered?`${raw.match(/^\d+/)?.[0]}. `:"";for(const wrapped of wrap(`${prefix}${clean}`,heading?70:88))all.push({text:wrapped,kind:heading?"heading":bullet||numbered?"bullet":"body"});all.push({text:"",kind:"space"});}}
  const pages:Line[][]=[];for(let offset=0;offset<all.length;offset+=36)pages.push(all.slice(offset,offset+36));if(!pages.length)pages.push([]);
  pages.forEach((page,index)=>{let commands=pdfRect(0,0,612,792,"1 1 1")+pdfRect(0,724,612,68,"0.043 0.114 0.212")+pdfRect(0,718,612,6,"0.831 0.686 0.216")+pdfText("ACCÈS CANADA",42,754,18,"F2","1 1 1")+pdfText(plainMarkdown(title),42,690,17,"F2","0.043 0.114 0.212")+pdfText(`${client.full_name} | ${client.file_reference||"Référence à attribuer"} | Version ${version}`,42,670,8,"F1","0.35 0.40 0.47")+pdfLine(42,657,570,657,"0.831 0.686 0.216",1);let y=635;for(const line of page){if(line.kind==="heading"){commands+=pdfRect(42,y-3,4,14,"0.831 0.686 0.216")+pdfText(line.text,54,y,11,"F2","0.043 0.114 0.212");y-=4;}else if(line.text)commands+=pdfText(line.text,line.kind==="bullet"?58:48,y,9.5,"F1","0.09 0.13 0.20");y-=line.kind==="space"?8:15;}commands+=premiumFooterCommands({documentNumber:`AC-JULIE-${String(version).padStart(3,"0")}`,verificationToken:null},index+1,pages.length);builder.addPage(commands);});return builder.finish();
}

export function validateGeneratedPdf(bytes:Buffer){const text=bytes.toString("latin1");if(bytes.length<800||!text.startsWith("%PDF-1.4\n%")||!text.endsWith("%%EOF\n"))throw new Error("Le PDF généré est vide ou sa structure est incomplète.");if(!text.includes("/Type /Catalog")||!text.includes("/Type /Page")||!text.includes("xref\n")||!text.includes("startxref\n"))throw new Error("Le PDF généré ne contient pas les objets obligatoires.");const match=text.match(/startxref\n(\d+)\n%%EOF/);const offset=Number(match?.[1]);if(!Number.isInteger(offset)||offset<=0||text.slice(offset,offset+4)!=="xref")throw new Error("La table de références du PDF est invalide.");return true;}
export function validateGeneratedDocx(bytes:Buffer){const binary=bytes.toString("latin1");if(bytes.length<1500||bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("Le document Word généré n’est pas une archive DOCX valide.");for(const entry of ["[Content_Types].xml","word/document.xml","word/_rels/document.xml.rels"])if(!binary.includes(entry))throw new Error(`Le document Word est incomplet : ${entry} manque.`);if(!binary.includes("PK\x05\x06"))throw new Error("Le répertoire central du document Word est absent.");return true;}

async function insertSmartDocument(input:Omit<SmartDocument,"id"|"created_at"|"word_upload_id"|"pdf_upload_id">){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify(input)}),"Création document intelligent");return((await response.json()) as SmartDocument[])[0];}
async function attachUploads(id:string,wordId:string,pdfId:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({word_upload_id:wordId,pdf_upload_id:pdfId})}),"Association fichiers intelligents");return((await response.json()) as SmartDocument[])[0];}

export async function createSmartDocument(input:{client:AdminClient;title:string;category:string;kind:SmartDocumentKind;sourceText:string;instruction?:string;parent?:SmartDocument|null}){
  const version=input.parent?input.parent.version+1:1;const improved=await improveText({source:input.sourceText,instruction:input.instruction,kind:input.kind,title:input.title,client:input.client});const root=input.parent?.parent_document_id||input.parent?.id||null;
  const base=`${slug(input.title)}-v${version}`,category=crmCategory(input.category);const [docx,pdf]=await Promise.all([generateProfessionalDocx(input.client,input.title,improved.text,version),Promise.resolve(generateProfessionalPdf(input.client,input.title,improved.text,version))]);
  validateGeneratedDocx(docx);validateGeneratedPdf(pdf);
  const record=await insertSmartDocument({client_id:input.client.id,parent_document_id:root,title:input.title,category:input.category,document_kind:input.kind,source_text:input.sourceText,professional_text:improved.text,edit_instruction:input.instruction||null,version,model:improved.model,created_by:"julie"});
  const wordFile=new File([new Uint8Array(docx)],`${base}.docx`,{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),pdfFile=new File([new Uint8Array(pdf)],`${base}.pdf`,{type:"application/pdf"});
  const [wordPath,pdfPath]=await Promise.all([uploadClientFile(input.client.id,wordFile),uploadClientFile(input.client.id,pdfFile)]);
  const common={client_id:input.client.id,category,version,status:"active" as const,replaced_document_id:null,deleted_at:null,uploaded_by:"julie"};
  const [wordUpload,pdfUpload]=await Promise.all([createClientUpload({...common,file_name:wordFile.name,file_path:wordPath,file_type:wordFile.type,file_size:wordFile.size}),createClientUpload({...common,file_name:pdfFile.name,file_path:pdfPath,file_type:pdfFile.type,file_size:pdfFile.size})]);
  return{record:await attachUploads(record.id,wordUpload.id,pdfUpload.id),wordUpload,pdfUpload,content:improved.text};
}
