import "server-only";

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { AlignmentType, BorderStyle, Document, Footer, Header, HeadingLevel, ImageRun, Packer, PageNumber, Paragraph, TextRun } from "docx";
import type { AdminClient } from "@/lib/admin-data";
import { createClientUpload, uploadClientFile } from "@/lib/client-portal";
import { assertMonthlyAiBudget, recordAiUsage } from "@/lib/ai-usage";
import { BrandedPdfBuilder, pdfLine, pdfRect, pdfText, premiumFooterCommands } from "@/lib/document-branding";
import { brand } from "@/lib/site";

export type SmartDocumentKind = "contrat"|"lettre"|"formulaire"|"questionnaire"|"checklist"|"procedure"|"modele"|"autre";
export type SmartDocument = { id:string;client_id:string;parent_document_id:string|null;title:string;category:string;document_kind:SmartDocumentKind;source_text:string;professional_text:string;edit_instruction:string|null;version:number;word_upload_id:string|null;pdf_upload_id:string|null;model:string|null;created_by:string;created_at:string };

function crmCategory(value:string){const text=value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase();if(text.includes("garant"))return "garant_financier";if(text.includes("formulaire"))return "formulaires_ircc";if(text.includes("financ"))return "situation_financiere";if(text.includes("emploi")||text.includes("contrat"))return "emploi_commerce";if(text.includes("lettre")||text.includes("correspond"))return "correspondance";return "acces_canada";}
function slug(value:string){return value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)||"document";}
function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Configuration Supabase manquante pour les documents intelligents.");return{url,key};}
function headers(prefer?:string){const{key}=config();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label} (${response.status}) : ${await response.text()}`);return response;}

export async function getSmartDocument(id:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,{headers:headers(),cache:"no-store"}),"Lecture document intelligent");return((await response.json()) as SmartDocument[])[0]||null;}
export async function listSmartDocuments(clientId:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?client_id=eq.${encodeURIComponent(clientId)}&select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"}),"Liste documents intelligents");return await response.json() as SmartDocument[];}

async function improveText(input:{source:string;instruction?:string;kind:SmartDocumentKind;title:string;client:AdminClient}){
  const token=process.env.OPENAI_API_KEY;if(!token)throw new Error("OPENAI_API_KEY n’est pas configurée.");
  await assertMonthlyAiBudget();const model=process.env.OPENAI_MODEL||"gpt-5.4";
  const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(45000),body:JSON.stringify({model,messages:[{role:"system",content:"Tu es la rédactrice administrative d’Accès Canada. Corrige l’orthographe et la grammaire, améliore la clarté et le ton professionnel, sans inventer aucun fait, montant, date, identité ou engagement juridique. Conserve les champs à compléter entre crochets. Retourne uniquement le texte final, avec titres simples et paragraphes séparés."},{role:"user",content:`Type: ${input.kind}\nTitre: ${input.title}\nClient: ${input.client.full_name} (${input.client.file_reference||"sans référence"})\nInstruction de modification: ${input.instruction||"Créer une version professionnelle fidèle"}\n\nTexte source:\n${input.source.slice(0,30000)}`}]}),});
  if(!response.ok){const detail=(await response.text()).slice(0,500);await recordAiUsage({clientId:input.client.id,feature:"smart_document",model,status:response.status===429?"quota_exceeded":"failed",errorCode:`HTTP_${response.status}`}).catch(()=>undefined);throw new Error(`Amélioration IA impossible (${response.status}) : ${detail}`);}
  const body=await response.json() as {choices?:Array<{message?:{content?:string}}>;usage?:{prompt_tokens?:number;completion_tokens?:number}};const text=body.choices?.[0]?.message?.content?.trim();if(!text)throw new Error("L’IA n’a produit aucun contenu.");await recordAiUsage({clientId:input.client.id,feature:"smart_document",model,inputTokens:body.usage?.prompt_tokens,outputTokens:body.usage?.completion_tokens}).catch(()=>undefined);return{text,model};
}

function paragraphs(text:string){return text.replace(/\r/g,"").split(/\n{2,}/).map(value=>value.trim()).filter(Boolean);}
function plainMarkdown(value:string){return value.replace(/^#{1,6}\s+/gm,"").replace(/\*\*(.*?)\*\*/g,"$1").replace(/__(.*?)__/g,"$1").replace(/^\s*[-*+]\s+/gm,"• ").replace(/`([^`]+)`/g,"$1").trim();}
function richRuns(value:string,options:{color:string;size:number;bold?:boolean}){const runs:TextRun[]=[];let cursor=0;const expression=/\*\*(.+?)\*\*|__(.+?)__/g;for(const match of value.matchAll(expression)){const index=match.index||0;if(index>cursor)runs.push(new TextRun({text:value.slice(cursor,index),color:options.color,size:options.size,bold:options.bold}));runs.push(new TextRun({text:match[1]||match[2],color:options.color,size:options.size,bold:true}));cursor=index+match[0].length;}if(cursor<value.length)runs.push(new TextRun({text:value.slice(cursor),color:options.color,size:options.size,bold:options.bold}));return runs.length?runs:[new TextRun({text:value,color:options.color,size:options.size,bold:options.bold})];}
async function generateDocx(client:AdminClient,title:string,content:string,version:number){
  let logo:Buffer|undefined;try{logo=await readFile(join(process.cwd(),"public","images","logo.png"));}catch{logo=undefined;}
  const navy="0B1D36",gold="D4AF37",red="C8102E";
  const headerChildren=[new Paragraph({alignment:AlignmentType.LEFT,border:{bottom:{color:gold,style:BorderStyle.SINGLE,size:16}},children:[...(logo?[new ImageRun({data:logo,transformation:{width:54,height:54},type:"png"})]:[]),new TextRun({text:"  ACCÈS CANADA",bold:true,color:navy,size:28})]})];
  const body=[new Paragraph({heading:HeadingLevel.TITLE,spacing:{before:180,after:100},children:[new TextRun({text:plainMarkdown(title),bold:true,color:navy,size:34})]}),new Paragraph({spacing:{after:260},children:[new TextRun({text:`Dossier : ${client.full_name} · ${client.file_reference||"Référence à attribuer"} · Version ${version}`,color:"667085",size:18})]}),...paragraphs(content).flatMap((block,index)=>{const lines=block.split("\n").map(v=>v.trim()).filter(Boolean);const heading=lines.length===1&&lines[0].length<90&&(/^(?:#{1,6}\s+|\*\*.+\*\*$|[A-ZÀ-ÖØ-Ý])/.test(lines[0]))&&index>0;const text=heading?plainMarkdown(lines.join(" ")):lines.join("\n");return[new Paragraph({heading:heading?HeadingLevel.HEADING_1:undefined,spacing:{before:heading?180:0,after:120,line:300},children:richRuns(text,{bold:heading,color:heading?navy:"172033",size:heading?25:22})})];})];
  const document=new Document({creator:"Julie · Accès Canada",title,description:`Document officiel Accès Canada pour ${client.full_name}`,styles:{default:{document:{run:{font:"Aptos",size:22,color:"172033"},paragraph:{spacing:{line:276,after:120}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",run:{font:"Aptos Display",size:34,bold:true,color:navy}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Aptos Display",size:25,bold:true,color:navy}}]},sections:[{properties:{page:{margin:{top:1080,right:1080,bottom:1080,left:1080}}},headers:{default:new Header({children:headerChildren})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,border:{top:{color:gold,style:BorderStyle.SINGLE,size:8}},children:[new TextRun({text:`${brand.phone} · ${brand.email} · Document confidentiel · Page `,color:"667085",size:16}),new TextRun({children:[PageNumber.CURRENT],bold:true,color:red,size:16})]})]})},children:body}]});
  return Buffer.from(await Packer.toBuffer(document));
}

function wrap(text:string,max=92){const words=text.replace(/\s+/g," ").trim().split(" "),lines:string[]=[];let line="";for(const word of words){if(`${line} ${word}`.trim().length>max&&line){lines.push(line);line=word;}else line=`${line} ${word}`.trim();}if(line)lines.push(line);return lines;}
function generatePdf(client:AdminClient,title:string,content:string,version:number){const builder=new BrandedPdfBuilder(),blocks=paragraphs(plainMarkdown(content)),pages:string[][]=[];let lines:string[]=[];for(const block of blocks){const wrapped=wrap(block);if(lines.length+wrapped.length+1>38){pages.push(lines);lines=[];}lines.push(...wrapped,"");}if(lines.length||!pages.length)pages.push(lines);pages.forEach((page,index)=>{let commands=pdfRect(0,0,612,792,"1 1 1")+pdfRect(0,724,612,68,"0.043 0.114 0.212")+pdfRect(0,718,612,6,"0.831 0.686 0.216")+pdfText("ACCÈS CANADA",42,754,18,"F2","1 1 1")+pdfText(plainMarkdown(title),42,690,17,"F2","0.043 0.114 0.212")+pdfText(`${client.full_name} | ${client.file_reference||"Référence à attribuer"} | Version ${version}`,42,670,8,"F1","0.35 0.40 0.47")+pdfLine(42,657,570,657,"0.831 0.686 0.216",1);let y=635;for(const line of page){if(line)commands+=pdfText(line,48,y,9.5,"F1","0.09 0.13 0.20");y-=14;}commands+=premiumFooterCommands({documentNumber:`AC-JULIE-${String(version).padStart(3,"0")}`,verificationToken:null},index+1,pages.length);builder.addPage(commands);});return builder.finish();}

export function validateGeneratedPdf(bytes:Buffer){const text=bytes.toString("latin1");if(bytes.length<800||!text.startsWith("%PDF-1.4\n%")||!text.endsWith("%%EOF\n"))throw new Error("Le PDF généré est vide ou sa structure est incomplète.");if(!text.includes("/Type /Catalog")||!text.includes("/Type /Page")||!text.includes("xref\n")||!text.includes("startxref\n"))throw new Error("Le PDF généré ne contient pas les objets obligatoires.");const match=text.match(/startxref\n(\d+)\n%%EOF/);const offset=Number(match?.[1]);if(!Number.isInteger(offset)||offset<=0||text.slice(offset,offset+4)!=="xref")throw new Error("La table de références du PDF est invalide.");return true;}
export function validateGeneratedDocx(bytes:Buffer){const binary=bytes.toString("latin1");if(bytes.length<1500||bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("Le document Word généré n’est pas une archive DOCX valide.");for(const entry of ["[Content_Types].xml","word/document.xml","word/_rels/document.xml.rels"])if(!binary.includes(entry))throw new Error(`Le document Word est incomplet : ${entry} manque.`);if(!binary.includes("PK\x05\x06"))throw new Error("Le répertoire central du document Word est absent.");return true;}

async function insertSmartDocument(input:Omit<SmartDocument,"id"|"created_at"|"word_upload_id"|"pdf_upload_id">){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify(input)}),"Création document intelligent");return((await response.json()) as SmartDocument[])[0];}
async function attachUploads(id:string,wordId:string,pdfId:string){const{url}=config();const response=await checked(await fetch(`${url}/rest/v1/julie_smart_documents?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({word_upload_id:wordId,pdf_upload_id:pdfId})}),"Association fichiers intelligents");return((await response.json()) as SmartDocument[])[0];}

export async function createSmartDocument(input:{client:AdminClient;title:string;category:string;kind:SmartDocumentKind;sourceText:string;instruction?:string;parent?:SmartDocument|null}){
  const version=input.parent?input.parent.version+1:1;const improved=await improveText({source:input.sourceText,instruction:input.instruction,kind:input.kind,title:input.title,client:input.client});const root=input.parent?.parent_document_id||input.parent?.id||null;
  const base=`${slug(input.title)}-v${version}`,category=crmCategory(input.category);const [docx,pdf]=await Promise.all([generateDocx(input.client,input.title,improved.text,version),Promise.resolve(generatePdf(input.client,input.title,improved.text,version))]);
  validateGeneratedDocx(docx);validateGeneratedPdf(pdf);
  const record=await insertSmartDocument({client_id:input.client.id,parent_document_id:root,title:input.title,category:input.category,document_kind:input.kind,source_text:input.sourceText,professional_text:improved.text,edit_instruction:input.instruction||null,version,model:improved.model,created_by:"julie"});
  const wordFile=new File([new Uint8Array(docx)],`${base}.docx`,{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),pdfFile=new File([new Uint8Array(pdf)],`${base}.pdf`,{type:"application/pdf"});
  const [wordPath,pdfPath]=await Promise.all([uploadClientFile(input.client.id,wordFile),uploadClientFile(input.client.id,pdfFile)]);
  const common={client_id:input.client.id,category,version,status:"active" as const,replaced_document_id:null,deleted_at:null,uploaded_by:"julie"};
  const [wordUpload,pdfUpload]=await Promise.all([createClientUpload({...common,file_name:wordFile.name,file_path:wordPath,file_type:wordFile.type,file_size:wordFile.size}),createClientUpload({...common,file_name:pdfFile.name,file_path:pdfPath,file_type:pdfFile.type,file_size:pdfFile.size})]);
  return{record:await attachUploads(record.id,wordUpload.id,pdfUpload.id),wordUpload,pdfUpload,content:improved.text};
}
