"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, Save } from "lucide-react";
import { calculateQuestionnaireProgress, questionnaireDefinitions, questionnaireLabels, type QuestionnaireType } from "@/lib/questionnaire-definitions";
import type { QuestionnaireAnswers } from "@/lib/questionnaires";

export function QuestionnaireForm({ type, initialAnswers, initialStatus, endpoint = "/api/questionnaire", admin = false }: { type: QuestionnaireType; initialAnswers: QuestionnaireAnswers; initialStatus: "draft" | "submitted"; endpoint?: string; admin?: boolean }) {
  const sections = questionnaireDefinitions[type]; const [answers, setAnswers] = useState<QuestionnaireAnswers>(initialAnswers); const [index, setIndex] = useState(0); const [state, setState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [message, setMessage] = useState("");
  const progress = useMemo(() => calculateQuestionnaireProgress(type, answers), [answers, type]);
  useEffect(() => { if (answers === initialAnswers) return; const timer = window.setTimeout(() => void save(false, true), 1200); return () => window.clearTimeout(timer); }, [answers]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(submit = false, silent = false) { setState("saving"); setMessage(""); const response = await fetch(endpoint, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers, submit }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setState("error"); setMessage(body.error || "La sauvegarde a échoué."); return false; } setState("saved"); if (!silent) setMessage(submit ? "Questionnaire soumis avec succès." : "Brouillon enregistré."); return true; }
  const section = sections[index];
  return <div className="grid gap-6 lg:grid-cols-[17rem_1fr]">
    <aside className="h-fit rounded-[1.75rem] bg-navy p-5 text-white lg:sticky lg:top-6"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Progression</p><p className="mt-3 text-3xl font-black">{progress} %</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-gold transition-all" style={{ width: `${progress}%` }} /></div><nav className="mt-5 space-y-1">{sections.map((item, i) => <button type="button" key={item.key} onClick={() => setIndex(i)} className={`w-full rounded-xl px-3 py-2 text-left text-xs font-bold ${i === index ? "bg-white text-navy" : "text-white/70 hover:bg-white/10"}`}>{i + 1}. {item.title}</button>)}</nav></aside>
    <section className="rounded-[1.75rem] bg-white p-5 shadow-premium sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-canada">{questionnaireLabels[type]}</p><h1 className="mt-2 font-display text-3xl font-black text-navy">{section.title}</h1>{section.description && <p className="mt-2 text-sm text-navy/60">{section.description}</p>}</div><span className="rounded-full bg-ivory px-3 py-2 text-xs font-black text-navy/60">Section {index + 1}/{sections.length}</span></div>
      <div className="mt-7 grid gap-5 md:grid-cols-2">{section.fields.map((field) => <label key={field.key} className={field.type === "textarea" ? "md:col-span-2" : ""}><span className="text-sm font-black text-navy">{field.label}{field.required && <span className="text-canada"> *</span>}</span>{field.type === "textarea" ? <textarea rows={4} value={String(answers[field.key] || "")} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.value })} className="mt-2 w-full rounded-2xl border border-navy/12 bg-ivory/50 px-4 py-3 text-navy" /> : field.type === "select" ? <select value={String(answers[field.key] || "")} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.value })} className="mt-2 w-full rounded-2xl border border-navy/12 bg-ivory/50 px-4 py-3 text-navy"><option value="">Sélectionner</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : field.type === "checkbox" ? <span className="mt-3 flex gap-3 rounded-2xl bg-ivory p-4"><input type="checkbox" checked={answers[field.key] === true} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.checked })} /><span className="text-sm font-bold text-navy/70">Je confirme</span></span> : <input type={field.type} value={String(answers[field.key] || "")} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.value })} className="mt-2 w-full rounded-2xl border border-navy/12 bg-ivory/50 px-4 py-3 text-navy" />}{field.help && <span className="mt-1 block text-xs text-navy/45">{field.help}</span>}</label>)}</div>
      {message && <p className={`mt-5 rounded-xl p-3 text-sm font-bold ${state === "error" ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{message}</p>}
      <div className="mt-8 flex flex-wrap justify-between gap-3"><button type="button" disabled={index === 0} onClick={() => setIndex((v) => v - 1)} className="inline-flex items-center gap-2 rounded-full bg-navy/8 px-5 py-3 font-black text-navy disabled:opacity-30"><ChevronLeft className="h-4 w-4" />Précédent</button><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void save(false)} className="inline-flex items-center gap-2 rounded-full border border-navy/15 px-5 py-3 font-black text-navy"><Save className="h-4 w-4" />{state === "saving" ? "Sauvegarde…" : "Enregistrer"}</button>{index < sections.length - 1 ? <button type="button" onClick={() => setIndex((v) => v + 1)} className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 font-black text-navy">Suivant<ChevronRight className="h-4 w-4" /></button> : <button type="button" disabled={progress < 100 || (initialStatus === "submitted" && !admin)} onClick={() => void save(true)} className="inline-flex items-center gap-2 rounded-full bg-canada px-5 py-3 font-black text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4" />Soumettre</button>}</div></div>
    </section>
  </div>;
}

