"use client";
import Link from "next/link"; import { useEffect, useRef, useState } from "react"; import { Bell, CheckCheck, Search, X } from "lucide-react"; import type { AdminNotification, UniversalSearchResult } from "@/lib/platform-v2";

export function AdminCommandCenter(){const[query,setQuery]=useState("");const[results,setResults]=useState<UniversalSearchResult[]>([]);const[notifications,setNotifications]=useState<AdminNotification[]>([]);const[showNotifications,setShowNotifications]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>{void loadNotifications();const timer=window.setInterval(()=>void loadNotifications(),30000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{controller.current?.abort();if(query.trim().length<2){setResults([]);return}const next=new AbortController();controller.current=next;const timer=window.setTimeout(async()=>{const response=await fetch(`/api/admin/search?q=${encodeURIComponent(query)}`,{signal:next.signal});if(response.ok)setResults(await response.json())},220);return()=>{window.clearTimeout(timer);next.abort()}},[query]);
 async function loadNotifications(){const response=await fetch("/api/admin/notifications");if(response.ok)setNotifications(await response.json())}
 async function markAll(){await fetch("/api/admin/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});await loadNotifications()}
 async function markRead(item:AdminNotification){if(item.status==="unread")await fetch("/api/admin/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status:"read"})});setShowNotifications(false);await loadNotifications()}
 const unread=notifications.filter((item)=>item.status==="unread").length;
 return <div className="flex w-full items-center justify-end gap-3"><div className="relative w-full max-w-xl"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-navy/35"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Recherche universelle…" aria-label="Recherche universelle" className="w-full rounded-full border border-navy/10 bg-white py-3 pl-11 pr-10 text-sm font-bold shadow-sm outline-none focus:border-gold"/>{query?<button onClick={()=>setQuery("")} aria-label="Effacer" className="absolute right-3 top-1/2 -translate-y-1/2"><X className="h-4 w-4"/></button>:null}{query.trim().length>=2?<div className="absolute inset-x-0 top-[calc(100%+8px)] z-50 max-h-[28rem] overflow-y-auto rounded-2xl border border-navy/10 bg-white p-2 shadow-2xl">{results.length?results.map((item)=><Link key={item.id} href={item.href} onClick={()=>setQuery("")} className="flex items-center justify-between rounded-xl px-4 py-3 hover:bg-gold/10"><span><strong className="block text-sm">{item.title}</strong><small className="text-navy/45">{item.subtitle}</small></span><span className="rounded-full bg-navy/5 px-2 py-1 text-[10px] font-black uppercase">{item.type}</span></Link>):<p className="p-4 text-sm font-bold text-navy/45">Aucun résultat.</p>}</div>:null}</div>
 <div className="relative"><button onClick={()=>setShowNotifications((value)=>!value)} aria-label={`${unread} notifications non lues`} className="relative grid h-12 w-12 place-items-center rounded-full bg-navy text-white"><Bell className="h-5 w-5"/>{unread?<span className="absolute -right-1 -top-1 grid h-6 min-w-6 place-items-center rounded-full bg-canada px-1 text-[10px] font-black">{unread>99?"99+":unread}</span>:null}</button>{showNotifications?<div className="absolute right-0 top-14 z-50 w-[min(24rem,calc(100vw-2rem))] rounded-3xl border border-navy/10 bg-white p-3 shadow-2xl"><div className="flex items-center justify-between px-2 py-2"><strong>Centre de notifications</strong>{unread?<button onClick={markAll} className="flex items-center gap-1 text-xs font-black text-canada"><CheckCheck className="h-4 w-4"/>Tout lire</button>:null}</div><div className="max-h-[32rem] space-y-1 overflow-y-auto">{notifications.length?notifications.map((item)=><Link key={item.id} href={item.href||"/admin"} onClick={()=>void markRead(item)} className={`block rounded-2xl p-3 ${item.status==="unread"?"bg-gold/12":"hover:bg-ivory"}`}><span className="flex items-start gap-2"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.severity==="urgent"?"bg-canada":item.severity==="success"?"bg-emerald-500":"bg-gold"}`}/><span><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs leading-5 text-navy/55">{item.message}</span><small className="mt-1 block font-bold text-navy/30">{new Date(item.created_at).toLocaleString("fr-CA")}</small></span></span></Link>):<p className="p-5 text-center text-sm text-navy/45">Aucune notification.</p>}</div></div>:null}</div></div>
}
