"use client";
import { useState } from "react";
import { Bot,ClipboardList,FileText,Mail,Sparkles } from "lucide-react";
import type { DossierAnalysis } from "@/lib/ai-assistant";
const actions=[
  ["resume_dossier","Résumer le dossier",Sparkles],
  ["preparation_ircc","Préparer le dossier IRCC",ClipboardList],
  ["courriel_professionnel","Préparer un courriel",Mail],
  ["lettre_explicative","Préparer une lettre",FileText],
  ["prochaines_actions","Proposer les actions",ClipboardList],
] as const;
export function ClientAiAssistant({clientId,analysis}:{clientId:string;analysis:DossierAnalysis}){
  const[output,setOutput]=useState(""),[loading,setLoading]=useState(""),[error,setError]=useState(""),[approval,setApproval]=useState(false);
  async function run(capability:string){setLoading(capability);setError("");setApproval(false);const response=await fetch(`/api/admin/clients/${clientId}/assistant`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({capability})});const data=await response.json() as{text?:string;error?:string;approvalRequired?:boolean};if(response.ok){setOutput(data.text||"");setApproval(Boolean(data.approvalRequired));}else setError(data.error||"Julie est indisponible.");setLoading("");}
  return <section className="rounded-[2rem] border border-gold/30 bg-gradient-to-br from-navy to-[#122d52] p-5 text-white shadow-premium md:p-7"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gold text-navy"><Bot/></span><div><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Assistante administrative</p><h2 className="font-display text-2xl font-black">Julie Mboyo</h2></div></div><p className="mt-5 text-sm leading-6 text-white/68">{analysis.summary}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{actions.map(([key,label,Icon])=><button key={key} type="button" disabled={Boolean(loading)} onClick={()=>run(key)} className="flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-left text-sm font-black transition hover:bg-gold hover:text-navy disabled:opacity-50"><Icon className="h-4 w-4"/>{loading===key?"Préparation…":label}</button>)}</div>{error?<p className="mt-4 rounded-xl bg-red-500/20 p-3 text-sm font-bold">{error}</p>:null}{approval?<p className="mt-4 rounded-xl border border-gold/30 bg-gold/10 p-3 text-sm font-bold text-gold">Ce brouillon a été placé dans la file d’approbation du directeur. Aucune transmission n’a été effectuée.</p>:null}{output?<div className="mt-5"><label className="text-xs font-black uppercase tracking-[.16em] text-gold">Brouillon modifiable — validation humaine obligatoire</label><textarea value={output} onChange={e=>setOutput(e.target.value)} rows={14} className="mt-2 w-full rounded-2xl bg-white p-4 text-sm leading-6 text-navy outline-none"/></div>:null}<div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><Insight title="Documents manquants" rows={analysis.missingDocuments}/><Insight title="Points à vérifier" rows={analysis.inconsistencies}/></div><p className="mt-4 text-xs text-white/45">Julie fournit une assistance administrative. Elle ne rend aucune décision juridique et ne soumet aucun dossier IRCC.</p></section>;
}
function Insight({title,rows}:{title:string;rows:string[]}){return <div className="rounded-2xl bg-white/8 p-4"><strong className="text-gold">{title}</strong><ul className="mt-2 space-y-1 text-white/65">{rows.slice(0,4).map(row=><li key={row}>• {row}</li>)}</ul></div>}
