"use client";

import { useState } from "react";
import type { ClientReminder, ClientTask } from "@/lib/crm";

export function ClientWorkflowManager({ clientId, initialTasks, initialReminders }: { clientId:string; initialTasks:ClientTask[]; initialReminders:ClientReminder[] }) {
  const [tasks,setTasks]=useState(initialTasks); const [reminders,setReminders]=useState(initialReminders); const [message,setMessage]=useState("");
  async function createTask(formData:FormData) { const response=await fetch(`/api/admin/clients/${clientId}/tasks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:formData.get("title"),priority:formData.get("priority"),dueAt:formData.get("dueAt")})}); if(response.ok){const saved=await response.json();setTasks((rows)=>[saved,...rows]);setMessage("Tâche créée.");} else setMessage("La tâche n’a pas pu être créée."); }
  async function setTaskStatus(id:string,status:ClientTask["status"]){const response=await fetch(`/api/admin/clients/${clientId}/tasks`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(response.ok){const saved=await response.json();setTasks((rows)=>rows.map((row)=>row.id===id?saved:row));}}
  async function createReminder(formData:FormData){const response=await fetch(`/api/admin/clients/${clientId}/reminders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:formData.get("reminderTitle"),message:formData.get("reminderMessage"),remindAt:formData.get("remindAt"),channel:formData.get("channel")})});if(response.ok){const saved=await response.json();setReminders((rows)=>[...rows,saved].sort((a,b)=>a.remind_at.localeCompare(b.remind_at)));setMessage("Rappel planifié.");}else setMessage("Le rappel n’a pas pu être planifié.");}
  async function cancelReminder(id:string){const response=await fetch(`/api/admin/clients/${clientId}/reminders`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"cancelled"})});if(response.ok){const saved=await response.json();setReminders((rows)=>rows.map((row)=>row.id===id?saved:row));}}
  return <div className="space-y-6">
    {message?<p role="status" className="rounded-xl bg-gold/20 px-4 py-3 text-sm font-black">{message}</p>:null}
    <div className="grid gap-5 lg:grid-cols-2">
      <form action={createTask} className="space-y-3 rounded-2xl bg-ivory p-4"><h3 className="font-black">Nouvelle tâche</h3><input required name="title" placeholder="Action à effectuer" className="w-full rounded-xl border border-navy/10 p-3"/><div className="grid gap-3 sm:grid-cols-2"><select name="priority" className="rounded-xl border border-navy/10 p-3"><option value="normal">Normale</option><option value="high">Haute</option><option value="urgent">Urgente</option><option value="low">Basse</option></select><input name="dueAt" type="datetime-local" className="rounded-xl border border-navy/10 p-3"/></div><button className="rounded-full bg-navy px-5 py-3 text-sm font-black text-white">Ajouter la tâche</button></form>
      <form action={createReminder} className="space-y-3 rounded-2xl bg-ivory p-4"><h3 className="font-black">Nouveau rappel</h3><input required name="reminderTitle" placeholder="Titre du rappel" className="w-full rounded-xl border border-navy/10 p-3"/><textarea required name="reminderMessage" placeholder="Message" className="w-full rounded-xl border border-navy/10 p-3"/><div className="grid gap-3 sm:grid-cols-2"><input required name="remindAt" type="datetime-local" className="rounded-xl border border-navy/10 p-3"/><select name="channel" className="rounded-xl border border-navy/10 p-3"><option value="admin">Administration</option><option value="email">Courriel client</option></select></div><button className="rounded-full bg-gold px-5 py-3 text-sm font-black text-navy">Planifier</button></form>
    </div>
    <div className="grid gap-5 lg:grid-cols-2"><div><h3 className="mb-3 font-black">Tâches</h3><div className="space-y-2">{tasks.length?tasks.map((task)=><div key={task.id} className="rounded-2xl border border-navy/10 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span><strong className="block">{task.title}</strong><small className="text-navy/45">{task.priority} · {task.due_at?new Date(task.due_at).toLocaleString("fr-CA"):"sans échéance"}</small></span><select aria-label={`Statut de ${task.title}`} value={task.status} onChange={(event)=>setTaskStatus(task.id,event.target.value as ClientTask["status"])} className="rounded-full bg-ivory px-3 py-2 text-xs font-black"><option value="todo">À faire</option><option value="in_progress">En cours</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select></div></div>):<p className="text-sm text-navy/50">Aucune tâche.</p>}</div></div>
    <div><h3 className="mb-3 font-black">Rappels</h3><div className="space-y-2">{reminders.length?reminders.map((reminder)=><div key={reminder.id} className="rounded-2xl border border-navy/10 p-4"><strong className="block">{reminder.title}</strong><p className="mt-1 text-sm text-navy/60">{reminder.message}</p><div className="mt-2 flex items-center justify-between"><small className="font-bold text-navy/40">{new Date(reminder.remind_at).toLocaleString("fr-CA")} · {reminder.status}</small>{reminder.status==="scheduled"?<button onClick={()=>cancelReminder(reminder.id)} className="text-xs font-black text-canada">Annuler</button>:null}</div></div>):<p className="text-sm text-navy/50">Aucun rappel.</p>}</div></div></div>
  </div>;
}
