"use client";
import { useState } from "react";
import { Copy, Download, Link2, Mail, Power } from "lucide-react";
import { questionnaireLabels, type QuestionnaireType } from "@/lib/questionnaire-definitions";
import type { QuestionnaireRecord } from "@/lib/questionnaires";

export function ClientQuestionnaires({ clientId, initialRows }: { clientId: string; initialRows: QuestionnaireRecord[] }) { const [rows, setRows] = useState(initialRows); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function action(type: QuestionnaireType, operation: "generate" | "disable", email = false) { setBusy(type); setMessage(""); const response = await fetch(`/api/admin/clients/${clientId}/questionnaires`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, operation, email }) }); const body = await response.json(); setBusy(""); if (!response.ok) return setMessage(body.error || "Action impossible."); if (body.url) { await navigator.clipboard.writeText(body.url).catch(() => undefined); setMessage(email ? "Lien régénéré, copié et envoyé par courriel." : "Nouveau lien sécurisé copié."); } else setMessage("Lien désactivé."); if (body.rows) setRows(body.rows); }
  return <div className="space-y-4">{message && <p className="rounded-xl bg-gold/12 p-3 text-sm font-bold text-navy">{message}</p>}{rows.map((row) => <article key={row.id} className="rounded-2xl border border-navy/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-navy">{questionnaireLabels[row.questionnaire_type]}</h3><p className="mt-1 text-xs font-bold text-navy/45">{row.status === "submitted" ? "Soumis" : "Brouillon"} · {row.progress_percent} % · Modifié {new Date(row.updated_at).toLocaleString("fr-CA")}</p>{row.submitted_at && <p className="mt-1 text-xs font-bold text-emerald-700">Soumis le {new Date(row.submitted_at).toLocaleString("fr-CA")}</p>}</div><span className="rounded-full bg-ivory px-3 py-2 text-xs font-black text-navy">{row.progress_percent} %</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-navy/8"><div className="h-full bg-gold" style={{ width: `${row.progress_percent}%` }} /></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy === row.questionnaire_type} onClick={() => void action(row.questionnaire_type, "generate")} className="inline-flex items-center gap-2 rounded-full bg-navy px-4 py-2 text-xs font-black text-white"><Link2 className="h-4 w-4" />Générer / régénérer</button><button onClick={() => void action(row.questionnaire_type, "generate", true)} className="inline-flex items-center gap-2 rounded-full bg-gold px-4 py-2 text-xs font-black text-navy"><Mail className="h-4 w-4" />Envoyer</button><a href={`/admin/clients/${clientId}/questionnaires/${row.questionnaire_type}`} className="inline-flex items-center gap-2 rounded-full border border-navy/15 px-4 py-2 text-xs font-black text-navy"><Copy className="h-4 w-4" />Voir / corriger</a><a href={`/api/admin/clients/${clientId}/questionnaires/${row.questionnaire_type}/pdf`} className="inline-flex items-center gap-2 rounded-full border border-navy/15 px-4 py-2 text-xs font-black text-navy"><Download className="h-4 w-4" />PDF</a><button onClick={() => void action(row.questionnaire_type, "disable")} className="inline-flex items-center gap-2 rounded-full border border-red-200 px-4 py-2 text-xs font-black text-red-700"><Power className="h-4 w-4" />Désactiver</button></div></article>)}</div>; }

