"use client";

import { DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { Download, ExternalLink, FileText, FolderOpen, Pencil, Send, ShieldCheck, Sparkles, Trash2, UploadCloud } from "lucide-react";

type Entry={role:"director"|"julie";content:string};
type Client={id:string;full_name:string;file_reference?:string|null};
type Uploaded={id:string;client_id:string;file_name:string;file_type?:string|null;category:string;status:string;created_at:string};
type Generated={id:string;client_id:string;client_name:string;file_name:string;document_label:string;status:string;created_at:string};
type UploadProgress={name:string;status:"waiting"|"uploading"|"completed"|"error";message?:string};
type Task={id:string;title:string;status:"todo"|"in_progress"|"completed"|"cancelled";priority:string;due_at:string|null};
type JulieAction={tool:string;status:"completed"|"needs_input"|"failed";label:string;clientId?:string};

export function JulieWorkspace(){
  const[entries,setEntries]=useState<Entry[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState("auto"),[uploads,setUploads]=useState<Uploaded[]>([]),[generated,setGenerated]=useState<Generated[]>([]);
  const[uploading,setUploading]=useState(false),[dragging,setDragging]=useState(false),[notice,setNotice]=useState("");
  const[uploadProgress,setUploadProgress]=useState<UploadProgress[]>([]);
  const[tasks,setTasks]=useState<Task[]>([]);
  const[actionResults,setActionResults]=useState<JulieAction[]>([]);
  const inputRef=useRef<HTMLInputElement>(null);
  const loadDocuments=useCallback(async()=>{const[u,g]=await Promise.all([fetch("/api/admin/client-uploads",{cache:"no-store"}),fetch("/api/admin/documents",{cache:"no-store"})]);if(u.ok){const data=await u.json() as{uploads?:Uploaded[]};setUploads((data.uploads||[]).filter(x=>x.status==="active"));}if(g.ok){const data=await g.json() as{documents?:Generated[]};setGenerated((data.documents||[]).filter(x=>x.status==="active"));}},[]);
  useEffect(()=>{fetch("/api/admin/julie").then(r=>r.json()).then((data:{messages?:Array<{role:string;content:string}>})=>setEntries(data.messages?.map(m=>({role:m.role==="julie"?"julie":"director",content:m.content}))||[])).catch(()=>setError("Historique indisponible."));fetch("/api/admin/clients").then(r=>r.json()).then((data:{clients?:Client[]})=>setClients([{id:"auto",full_name:"Détection automatique par Julie"},...(data.clients||[])])).catch(()=>setError("Dossiers clients indisponibles."));void loadDocuments();const timer=window.setInterval(loadDocuments,5000);const focus=()=>void loadDocuments();window.addEventListener("focus",focus);return()=>{window.clearInterval(timer);window.removeEventListener("focus",focus);};},[loadDocuments]);
  useEffect(()=>{if(clientId==="auto"){setTasks([]);return;}fetch(`/api/admin/clients/${clientId}/tasks`,{cache:"no-store"}).then(r=>r.json()).then((data:{tasks?:Task[]})=>setTasks(data.tasks||[])).catch(()=>setTasks([]));},[clientId,entries]);
  async function send(){const value=message.trim();if(!value||busy)return;setEntries(v=>[...v,{role:"director",content:value}]);setMessage("");setBusy(true);setError("");setActionResults([]);try{const r=await fetch("/api/admin/julie",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,clientId:clientId||undefined})}),data=await r.json() as{answer?:string;error?:string;actions?:JulieAction[]};if(r.ok){setEntries(v=>[...v,{role:"julie",content:data.answer||"Demande reçue."}]);setActionResults(data.actions||[]);}else setError(data.error||"Julie est indisponible.");}finally{setBusy(false);}}
  async function importFiles(files:File[]){
    if(!files.length)return;
    setUploading(true);setNotice(`Julie traite ${files.length} document${files.length>1?"s":""}…`);
    setUploadProgress(files.map(file=>({name:file.name,status:"waiting"})));
    let completed=0;
    let cursor=0;
    async function worker(){
      while(cursor<files.length){
      const index=cursor++,file=files[index];
      setUploadProgress(current=>current.map((row,i)=>i===index?{...row,status:"uploading"}:row));
      const form=new FormData();if(clientId!=="auto")form.set("clientId",clientId);form.append("files",file);
      try{
        const response=await fetch("/api/admin/client-uploads",{method:"POST",body:form});
        const data=await response.json() as{message?:string;uploads?:Uploaded[]};
        if(!response.ok)throw new Error(data.message||"Importation impossible.");
        completed++;
        const analysis=(data.uploads?.[0] as Uploaded&{analysis?:{detected_type?:string;confidence?:number}}|undefined)?.analysis;
        setUploadProgress(current=>current.map((row,i)=>i===index?{...row,status:"completed",message:analysis?.detected_type?`${analysis.detected_type} · ${Math.round((analysis.confidence||0)*100)} %`:"Importé et classé"}:row));
      }catch(error){
        setUploadProgress(current=>current.map((row,i)=>i===index?{...row,status:"error",message:error instanceof Error?error.message:"Erreur inconnue"}:row));
      }
      }
    }
    await Promise.all(Array.from({length:Math.min(3,files.length)},()=>worker()));
    setNotice(`${completed}/${files.length} document(s) importé(s), analysé(s) et classé(s).`);
    await loadDocuments();setUploading(false);if(inputRef.current)inputRef.current.value="";
  }
  function drop(event:DragEvent<HTMLDivElement>){event.preventDefault();setDragging(false);void importFiles(Array.from(event.dataTransfer.files));}
  async function rename(kind:"upload"|"generated",item:Uploaded|Generated){const name=window.prompt("Nouveau nom du document",item.file_name)?.trim();if(!name||name===item.file_name)return;const base=kind==="upload"?`/api/admin/client-uploads/${item.id}?clientId=${item.client_id}`:`/api/admin/documents/${item.id}`;const r=await fetch(base,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({file_name:name})});setNotice(r.ok?"Document renommé.":"Impossible de renommer le document.");if(r.ok)await loadDocuments();}
  async function remove(kind:"upload"|"generated",item:Uploaded|Generated){if(!window.confirm(`Supprimer « ${item.file_name} » ?`))return;const base=kind==="upload"?`/api/admin/client-uploads/${item.id}?clientId=${item.client_id}`:`/api/admin/documents/${item.id}`;const r=await fetch(base,{method:"DELETE"});setNotice(r.ok?"Document supprimé.":"Impossible de supprimer le document.");if(r.ok)await loadDocuments();}
  async function setTaskStatus(task:Task,status:Task["status"]){const r=await fetch(`/api/admin/clients/${clientId}/tasks`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:task.id,status})});if(r.ok)setTasks(current=>current.map(item=>item.id===task.id?{...item,status}:item));}
  const clientName=(id:string)=>clients.find(c=>c.id===id)?.full_name||"Client";
  return <div className="space-y-6">
    {actionResults.length?<section className="rounded-[2rem] bg-white p-5 shadow-premium" aria-label="Résultats des actions de Julie"><h2 className="font-display text-xl font-black">Actions exécutées</h2><div className="mt-3 grid gap-2">{actionResults.map((result,index)=><article key={`${result.tool}-${index}`} className="flex items-start gap-3 rounded-xl border border-navy/10 p-3"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${result.status==="completed"?"bg-emerald-500":result.status==="failed"?"bg-red-500":"bg-amber-500"}`}/><div><p className="text-xs font-black uppercase tracking-wider text-navy/45">{result.status==="completed"?"Terminée":result.status==="failed"?"Échec":"Information requise"}</p><p className="text-sm font-bold">{result.label}</p>{result.clientId?<a className="mt-1 inline-block text-xs font-black text-canada underline" href={`/admin/clients/${result.clientId}`}>Ouvrir le dossier</a>:null}</div></article>)}</div></section>:null}
    {clientId!=="auto"?<section className="rounded-[2rem] bg-white p-5 shadow-premium"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-canada">Plan de travail</p><h2 className="mt-1 font-display text-2xl font-black">Tâches proposées et suivies par Julie</h2></div><span className="rounded-full bg-gold/20 px-3 py-2 text-xs font-black">{tasks.filter(task=>!['completed','cancelled'].includes(task.status)).length} ouverte(s)</span></div><div className="mt-4 grid gap-2">{tasks.filter(task=>task.status!=="cancelled").map(task=><article key={task.id} className="flex flex-col gap-3 rounded-xl border border-navy/10 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{task.title}</p><p className="text-xs text-navy/45">{task.priority}{task.due_at?` · ${new Date(task.due_at).toLocaleString("fr-CA")}`:""}</p></div><select aria-label={`Statut de ${task.title}`} value={task.status} onChange={event=>void setTaskStatus(task,event.target.value as Task["status"])} className="rounded-xl border border-navy/10 px-3 py-2 text-xs font-black"><option value="todo">À faire</option><option value="in_progress">En cours</option><option value="completed">Terminé</option></select></article>)}{!tasks.length?<p className="rounded-xl bg-ivory p-4 text-sm font-bold text-navy/45">Aucune tâche. Demandez à Julie de préparer les prochaines étapes.</p>:null}</div></section>:null}
    {uploadProgress.length?<section className="rounded-[2rem] bg-white p-5 shadow-premium" aria-label="Progression des importations"><h2 className="font-black text-navy">Progression de l’importation</h2><ul className="mt-3 grid gap-2 md:grid-cols-2">{uploadProgress.map((file,index)=><li key={`${file.name}-${index}`} className="rounded-xl border border-navy/10 p-3 text-xs"><div className="flex items-center justify-between gap-2"><span className="truncate font-black">{file.name}</span><span className={file.status==="error"?"text-red-700":file.status==="completed"?"text-emerald-700":"text-navy/50"}>{file.status==="waiting"?"En attente":file.status==="uploading"?"Analyse…":file.status==="completed"?"Terminé":"Erreur"}</span></div>{file.message?<p className="mt-1 text-navy/55">{file.message}</p>:null}</li>)}</ul></section>:null}
    <div className="grid min-w-0 gap-6 2xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className="min-w-0 overflow-hidden rounded-[2rem] bg-white shadow-premium"><div className="border-b border-navy/10 bg-navy p-5 text-white md:p-6"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gold text-navy"><Sparkles/></span><div><h2 className="font-display text-2xl font-black">Julie Mboyo</h2><p className="text-sm text-white/55">Assistante administrative du directeur</p></div></div></div><div className="h-[min(52vh,620px)] min-h-80 space-y-4 overflow-y-auto bg-ivory/60 p-4 md:p-5">{entries.length?entries.map((entry,index)=><div key={index} className={`max-w-[92%] break-words rounded-2xl p-4 text-sm leading-6 md:max-w-[85%] ${entry.role==="julie"?"bg-white text-navy shadow-sm":"ml-auto bg-navy text-white"}`}><strong className="mb-1 block text-xs uppercase tracking-wider text-gold">{entry.role==="julie"?"Julie":"Christian"}</strong><div className="whitespace-pre-wrap">{entry.content}</div></div>):<p className="rounded-2xl bg-white p-4 text-sm text-navy/55">Bonjour Christian. Je suis prête à gérer vos documents et votre travail administratif.</p>}{busy&&<p className="text-sm font-bold text-navy/45">Julie prépare sa réponse…</p>}</div><div className="border-t border-navy/10 p-4"><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey))void send();}} rows={3} placeholder="Julie, montre-moi les dossiers incomplets…" className="w-full resize-y rounded-2xl border border-navy/15 p-4 outline-none focus:ring-2 focus:ring-gold"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3">{error?<p className="text-sm font-bold text-red-700">{error}</p>:<span className="text-xs text-navy/40">Ctrl + Entrée pour envoyer</span>}<button onClick={send} disabled={busy||!message.trim()} className="inline-flex items-center gap-2 rounded-xl bg-gold px-5 py-3 font-black text-navy disabled:opacity-40"><Send className="h-4 w-4"/>Envoyer</button></div></div></section>
      <aside className="min-w-0 space-y-5"><section className="rounded-[2rem] bg-navy p-5 text-white shadow-premium md:p-6"><ShieldCheck className="h-9 w-9 text-gold"/><h3 className="mt-4 font-display text-xl font-black">Contrôle du directeur</h3><p className="mt-3 text-sm leading-6 text-white/65">Les actions officielles, juridiques ou financières restent soumises à votre approbation.</p></section><section className="rounded-[2rem] bg-white p-5 shadow-premium"><label className="text-xs font-black uppercase tracking-wider text-navy/55">Dossier client<select value={clientId} onChange={e=>setClientId(e.target.value)} className="mt-2 block w-full rounded-2xl border border-navy/10 bg-ivory p-3 text-sm normal-case tracking-normal">{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.file_reference?` — ${c.file_reference}`:""}</option>)}</select></label><div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`mt-4 rounded-3xl border-2 border-dashed p-6 text-center transition ${dragging?"border-gold bg-gold/20":"border-navy/15 bg-ivory"}`}><UploadCloud className="mx-auto h-9 w-9 text-canada"/><p className="mt-3 font-black text-navy">Déposez vos fichiers ici</p><p className="mt-1 text-xs leading-5 text-navy/50">PDF, JPG, PNG ou Word · plusieurs fichiers acceptés</p><input ref={inputRef} className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={e=>void importFiles(Array.from(e.target.files||[]))}/><button type="button" disabled={uploading||!clientId} onClick={()=>inputRef.current?.click()} className="mt-4 inline-flex items-center gap-2 rounded-full bg-canada px-4 py-3 text-sm font-black text-white disabled:opacity-50"><FolderOpen className="h-4 w-4"/>{uploading?"Analyse en cours…":"Importer des documents"}</button></div>{notice&&<p role="status" className="mt-4 rounded-2xl bg-gold/15 p-3 text-sm font-bold text-navy">{notice}</p>}</section></aside>
    </div>
    <section className="min-w-0 rounded-[2rem] bg-white p-5 shadow-premium md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-canada">Documents disponibles</p><h2 className="mt-2 font-display text-2xl font-black md:text-3xl">Documents reçus et générés</h2></div><span className="rounded-full bg-gold/20 px-4 py-2 text-xs font-black">{uploads.length+generated.length} documents</span></div><div className="mt-6 grid min-w-0 gap-3">{[...generated.map(x=>({kind:"generated" as const,item:x})),...uploads.map(x=>({kind:"upload" as const,item:x}))].map(({kind,item})=>{const url=kind==="generated"?`/api/admin/documents/${item.id}/download`:`/api/admin/client-uploads/${item.id}/download?clientId=${item.client_id}`;return <article key={`${kind}-${item.id}`} className="flex min-w-0 flex-col gap-4 rounded-2xl border border-navy/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-navy/5 text-canada"><FileText className="h-5 w-5"/></span><div className="min-w-0"><p className="truncate font-black">{item.file_name}</p><p className="truncate text-xs font-bold text-navy/45">{kind==="generated"?(item as Generated).document_label:"Document classé par Julie"} · {kind==="generated"?(item as Generated).client_name:clientName(item.client_id)}</p></div></div><div className="flex shrink-0 flex-wrap gap-2"><a href={`${url}${kind==="upload"?"&":"?"}disposition=inline`} target="_blank" rel="noreferrer" className="action" title="Ouvrir"><ExternalLink className="h-4 w-4"/></a><a href={url} className="action" title="Télécharger"><Download className="h-4 w-4"/></a><button className="action" title="Renommer" onClick={()=>void rename(kind,item)}><Pencil className="h-4 w-4"/></button><button className="grid h-10 w-10 place-items-center rounded-full bg-canada/10 text-canada hover:bg-canada hover:text-white" title="Supprimer" onClick={()=>void remove(kind,item)}><Trash2 className="h-4 w-4"/></button></div></article>})}{!uploads.length&&!generated.length?<p className="rounded-2xl bg-ivory p-5 text-sm font-bold text-navy/50">Aucun document disponible.</p>:null}</div></section>
  </div>;
}
