"use client";

import { DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { Download, ExternalLink, FileText, FolderOpen, Pencil, Send, ShieldCheck, Sparkles, Trash2, UploadCloud } from "lucide-react";

type Entry={role:"director"|"julie";content:string};
type Client={id:string;full_name:string;file_reference?:string|null};
type Uploaded={id:string;client_id:string;file_name:string;file_type?:string|null;category:string;status:string;created_at:string};
type Generated={id:string;client_id:string;client_name:string;file_name:string;document_label:string;status:string;created_at:string};

export function JulieWorkspace(){
  const[entries,setEntries]=useState<Entry[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState(""),[uploads,setUploads]=useState<Uploaded[]>([]),[generated,setGenerated]=useState<Generated[]>([]);
  const[uploading,setUploading]=useState(false),[dragging,setDragging]=useState(false),[notice,setNotice]=useState("");
  const inputRef=useRef<HTMLInputElement>(null);
  const loadDocuments=useCallback(async()=>{const[u,g]=await Promise.all([fetch("/api/admin/client-uploads",{cache:"no-store"}),fetch("/api/admin/documents",{cache:"no-store"})]);if(u.ok){const data=await u.json() as{uploads?:Uploaded[]};setUploads((data.uploads||[]).filter(x=>x.status==="active"));}if(g.ok){const data=await g.json() as{documents?:Generated[]};setGenerated((data.documents||[]).filter(x=>x.status==="active"));}},[]);
  useEffect(()=>{fetch("/api/admin/julie").then(r=>r.json()).then((data:{messages?:Array<{role:string;content:string}>})=>setEntries(data.messages?.map(m=>({role:m.role==="julie"?"julie":"director",content:m.content}))||[])).catch(()=>setError("Historique indisponible."));fetch("/api/admin/clients").then(r=>r.json()).then((data:{clients?:Client[]})=>{setClients(data.clients||[]);setClientId(data.clients?.[0]?.id||"");}).catch(()=>setError("Dossiers clients indisponibles."));void loadDocuments();const timer=window.setInterval(loadDocuments,5000);const focus=()=>void loadDocuments();window.addEventListener("focus",focus);return()=>{window.clearInterval(timer);window.removeEventListener("focus",focus);};},[loadDocuments]);
  async function send(){const value=message.trim();if(!value||busy)return;setEntries(v=>[...v,{role:"director",content:value}]);setMessage("");setBusy(true);setError("");try{const r=await fetch("/api/admin/julie",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,clientId:clientId||undefined})}),data=await r.json() as{answer?:string;error?:string};if(r.ok)setEntries(v=>[...v,{role:"julie",content:data.answer||"Demande reçue."}]);else setError(data.error||"Julie est indisponible.");}finally{setBusy(false);}}
  async function importFiles(files:File[]){if(!clientId){setNotice("Sélectionnez le dossier client avant l’importation.");return;}if(!files.length)return;setUploading(true);setNotice(`Julie analyse ${files.length} document${files.length>1?"s":""}…`);const form=new FormData();form.set("clientId",clientId);files.forEach(file=>form.append("files",file));try{const r=await fetch("/api/admin/client-uploads",{method:"POST",body:form});const data=await r.json() as{message?:string;uploads?:Uploaded[]};if(!r.ok)throw new Error(data.message||"Importation impossible.");setNotice(`${data.uploads?.length||files.length} document${files.length>1?"s":""} analysé${files.length>1?"s":""}, renommé${files.length>1?"s":""} et classé${files.length>1?"s":""} par Julie.`);await loadDocuments();}catch(e){setNotice(e instanceof Error?e.message:"Importation impossible.");}finally{setUploading(false);if(inputRef.current)inputRef.current.value="";}}
  function drop(event:DragEvent<HTMLDivElement>){event.preventDefault();setDragging(false);void importFiles(Array.from(event.dataTransfer.files));}
  async function rename(kind:"upload"|"generated",item:Uploaded|Generated){const name=window.prompt("Nouveau nom du document",item.file_name)?.trim();if(!name||name===item.file_name)return;const base=kind==="upload"?`/api/admin/client-uploads/${item.id}?clientId=${item.client_id}`:`/api/admin/documents/${item.id}`;const r=await fetch(base,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({file_name:name})});setNotice(r.ok?"Document renommé.":"Impossible de renommer le document.");if(r.ok)await loadDocuments();}
  async function remove(kind:"upload"|"generated",item:Uploaded|Generated){if(!window.confirm(`Supprimer « ${item.file_name} » ?`))return;const base=kind==="upload"?`/api/admin/client-uploads/${item.id}?clientId=${item.client_id}`:`/api/admin/documents/${item.id}`;const r=await fetch(base,{method:"DELETE"});setNotice(r.ok?"Document supprimé.":"Impossible de supprimer le document.");if(r.ok)await loadDocuments();}
  const clientName=(id:string)=>clients.find(c=>c.id===id)?.full_name||"Client";
  return <div className="space-y-6">
    <div className="grid min-w-0 gap-6 2xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className="min-w-0 overflow-hidden rounded-[2rem] bg-white shadow-premium"><div className="border-b border-navy/10 bg-navy p-5 text-white md:p-6"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gold text-navy"><Sparkles/></span><div><h2 className="font-display text-2xl font-black">Julie Mboyo</h2><p className="text-sm text-white/55">Assistante administrative du directeur</p></div></div></div><div className="h-[min(52vh,620px)] min-h-80 space-y-4 overflow-y-auto bg-ivory/60 p-4 md:p-5">{entries.length?entries.map((entry,index)=><div key={index} className={`max-w-[92%] break-words rounded-2xl p-4 text-sm leading-6 md:max-w-[85%] ${entry.role==="julie"?"bg-white text-navy shadow-sm":"ml-auto bg-navy text-white"}`}><strong className="mb-1 block text-xs uppercase tracking-wider text-gold">{entry.role==="julie"?"Julie":"Christian"}</strong><div className="whitespace-pre-wrap">{entry.content}</div></div>):<p className="rounded-2xl bg-white p-4 text-sm text-navy/55">Bonjour Christian. Je suis prête à gérer vos documents et votre travail administratif.</p>}{busy&&<p className="text-sm font-bold text-navy/45">Julie prépare sa réponse…</p>}</div><div className="border-t border-navy/10 p-4"><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey))void send();}} rows={3} placeholder="Julie, montre-moi les dossiers incomplets…" className="w-full resize-y rounded-2xl border border-navy/15 p-4 outline-none focus:ring-2 focus:ring-gold"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3">{error?<p className="text-sm font-bold text-red-700">{error}</p>:<span className="text-xs text-navy/40">Ctrl + Entrée pour envoyer</span>}<button onClick={send} disabled={busy||!message.trim()} className="inline-flex items-center gap-2 rounded-xl bg-gold px-5 py-3 font-black text-navy disabled:opacity-40"><Send className="h-4 w-4"/>Envoyer</button></div></div></section>
      <aside className="min-w-0 space-y-5"><section className="rounded-[2rem] bg-navy p-5 text-white shadow-premium md:p-6"><ShieldCheck className="h-9 w-9 text-gold"/><h3 className="mt-4 font-display text-xl font-black">Contrôle du directeur</h3><p className="mt-3 text-sm leading-6 text-white/65">Les actions officielles, juridiques ou financières restent soumises à votre approbation.</p></section><section className="rounded-[2rem] bg-white p-5 shadow-premium"><label className="text-xs font-black uppercase tracking-wider text-navy/55">Dossier client<select value={clientId} onChange={e=>setClientId(e.target.value)} className="mt-2 block w-full rounded-2xl border border-navy/10 bg-ivory p-3 text-sm normal-case tracking-normal">{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.file_reference?` — ${c.file_reference}`:""}</option>)}</select></label><div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`mt-4 rounded-3xl border-2 border-dashed p-6 text-center transition ${dragging?"border-gold bg-gold/20":"border-navy/15 bg-ivory"}`}><UploadCloud className="mx-auto h-9 w-9 text-canada"/><p className="mt-3 font-black text-navy">Déposez vos fichiers ici</p><p className="mt-1 text-xs leading-5 text-navy/50">PDF, JPG, PNG ou Word · plusieurs fichiers acceptés</p><input ref={inputRef} className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={e=>void importFiles(Array.from(e.target.files||[]))}/><button type="button" disabled={uploading||!clientId} onClick={()=>inputRef.current?.click()} className="mt-4 inline-flex items-center gap-2 rounded-full bg-canada px-4 py-3 text-sm font-black text-white disabled:opacity-50"><FolderOpen className="h-4 w-4"/>{uploading?"Analyse en cours…":"Importer des documents"}</button></div>{notice&&<p role="status" className="mt-4 rounded-2xl bg-gold/15 p-3 text-sm font-bold text-navy">{notice}</p>}</section></aside>
    </div>
    <section className="min-w-0 rounded-[2rem] bg-white p-5 shadow-premium md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-canada">Documents disponibles</p><h2 className="mt-2 font-display text-2xl font-black md:text-3xl">Documents reçus et générés</h2></div><span className="rounded-full bg-gold/20 px-4 py-2 text-xs font-black">{uploads.length+generated.length} documents</span></div><div className="mt-6 grid min-w-0 gap-3">{[...generated.map(x=>({kind:"generated" as const,item:x})),...uploads.map(x=>({kind:"upload" as const,item:x}))].map(({kind,item})=>{const url=kind==="generated"?`/api/admin/documents/${item.id}/download`:`/api/admin/client-uploads/${item.id}/download?clientId=${item.client_id}`;return <article key={`${kind}-${item.id}`} className="flex min-w-0 flex-col gap-4 rounded-2xl border border-navy/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-navy/5 text-canada"><FileText className="h-5 w-5"/></span><div className="min-w-0"><p className="truncate font-black">{item.file_name}</p><p className="truncate text-xs font-bold text-navy/45">{kind==="generated"?(item as Generated).document_label:"Document classé par Julie"} · {kind==="generated"?(item as Generated).client_name:clientName(item.client_id)}</p></div></div><div className="flex shrink-0 flex-wrap gap-2"><a href={`${url}${kind==="upload"?"&":"?"}disposition=inline`} target="_blank" rel="noreferrer" className="action" title="Ouvrir"><ExternalLink className="h-4 w-4"/></a><a href={url} className="action" title="Télécharger"><Download className="h-4 w-4"/></a><button className="action" title="Renommer" onClick={()=>void rename(kind,item)}><Pencil className="h-4 w-4"/></button><button className="grid h-10 w-10 place-items-center rounded-full bg-canada/10 text-canada hover:bg-canada hover:text-white" title="Supprimer" onClick={()=>void remove(kind,item)}><Trash2 className="h-4 w-4"/></button></div></article>})}{!uploads.length&&!generated.length?<p className="rounded-2xl bg-ivory p-5 text-sm font-bold text-navy/50">Aucun document disponible.</p>:null}</div></section>
  </div>;
}
