"use client";

import { useState } from "react";
import type { JulieApproval } from "@/lib/julie";
import { DOCUMENT_CATEGORIES } from "@/lib/document-categories";

type Notice={kind:"success"|"error";text:string};
const approvalDateFormatter=new Intl.DateTimeFormat("fr-CA",{dateStyle:"medium",timeStyle:"medium",timeZone:"America/Toronto"});
function formatApprovalDate(value:string){return approvalDateFormatter.format(new Date(value));}

export function JulieApprovalQueue({initial}:{initial:JulieApproval[]}){
  const[rows,setRows]=useState(initial),[history,setHistory]=useState<JulieApproval[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState<Notice|null>(null),[showHistory,setShowHistory]=useState(false),[categories,setCategories]=useState<Record<string,string>>({});

  async function loadHistory(){const response=await fetch("/api/admin/julie/approvals?status=all",{cache:"no-store"});const data=await response.json() as JulieApproval[]|{error?:string};if(!response.ok||!Array.isArray(data))throw new Error(!Array.isArray(data)&&data.error||"Historique indisponible.");setHistory(data.filter(row=>row.status!=="pending"));}
  async function toggleHistory(){try{if(!showHistory)await loadHistory();setShowHistory(value=>!value);setNotice(null);}catch(error){setNotice({kind:"error",text:error instanceof Error?error.message:"Historique indisponible."});}}
  async function decide(row:JulieApproval,status:"approved"|"rejected"){
    const category=categories[row.id]||String(row.payload.suggestedCategory||"");
    if(status==="approved"&&row.action_type==="document_review"&&(!category||category==="a_verifier")){setNotice({kind:"error",text:"Choisissez la catégorie correcte avant d’approuver ce document."});return;}
    setBusy(row.id);setNotice(null);
    try{const response=await fetch("/api/admin/julie/approvals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,status,category})});const data=await response.json() as JulieApproval&{message?:string;error?:string};if(!response.ok)throw new Error(data.message||data.error||`La décision a échoué (HTTP ${response.status}).`);setRows(current=>current.filter(item=>item.id!==row.id));setHistory(current=>[data,...current.filter(item=>item.id!==row.id)]);setNotice({kind:"success",text:data.message||(status==="approved"?"Action exécutée avec succès.":"Demande refusée.")});}catch(error){setNotice({kind:"error",text:error instanceof Error?error.message:"Décision impossible."});}finally{setBusy("");}
  }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-navy/55">{rows.length} demande(s) en attente</p><button type="button" onClick={()=>void toggleHistory()} className="rounded-xl border border-navy/15 px-4 py-2 text-sm font-black">{showHistory?"Masquer l’historique":"Afficher l’historique"}</button></div>
    {notice?<div role="status" aria-live="polite" className={`rounded-2xl p-4 text-sm font-bold ${notice.kind==="success"?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-800"}`}>{notice.text}</div>:null}
    {rows.length?<div className="space-y-4">{rows.map(row=><article key={row.id} className="rounded-[2rem] bg-white p-6 shadow-premium"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1"><span className="rounded-full bg-gold/15 px-3 py-1 text-xs font-black uppercase">{row.action_type.replaceAll("_"," ")}</span><h2 className="mt-3 font-display text-2xl font-black">{row.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-navy/60">{row.description}</p>{row.action_type==="document_review"?<label className="mt-4 block max-w-sm text-xs font-black uppercase tracking-wider text-navy/55">Catégorie à appliquer<select value={categories[row.id]||String(row.payload.suggestedCategory||"a_verifier")} onChange={event=>setCategories(current=>({...current,[row.id]:event.target.value}))} className="mt-2 block w-full rounded-xl border border-navy/15 bg-ivory p-3 text-sm normal-case tracking-normal"><option value="a_verifier">Choisir une catégorie…</option>{DOCUMENT_CATEGORIES.filter(item=>item.value!=="a_verifier").map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>:null}<small className="mt-3 block font-bold text-navy/35">Préparé par Julie · {formatApprovalDate(row.created_at)}</small></div><div className="flex gap-2"><button disabled={busy===row.id} onClick={()=>void decide(row,"rejected")} className="rounded-xl border border-red-200 px-4 py-3 font-black text-red-700 disabled:opacity-50">{busy===row.id?"Traitement…":"Refuser"}</button><button disabled={busy===row.id} onClick={()=>void decide(row,"approved")} className="rounded-xl bg-gold px-5 py-3 font-black text-navy disabled:opacity-50">{busy===row.id?"Exécution…":"Approuver et exécuter"}</button></div></div></article>)}</div>:<div className="rounded-[2rem] bg-white p-10 text-center shadow-premium"><h2 className="font-display text-2xl font-black">Aucune approbation en attente</h2><p className="mt-2 text-navy/50">Toutes les demandes ont été traitées.</p></div>}
    {showHistory?<section className="rounded-[2rem] bg-white p-6 shadow-premium"><h2 className="font-display text-2xl font-black">Historique des approbations</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-navy/10 text-xs uppercase text-navy/45"><th className="p-3">Action</th><th className="p-3">Statut</th><th className="p-3">Décision</th><th className="p-3">Approuvé par</th><th className="p-3">Durée</th><th className="p-3">Résultat</th></tr></thead><tbody>{history.map(row=><tr key={row.id} className="border-b border-navy/5 align-top"><td className="p-3 font-bold">{row.title}</td><td className="p-3 font-black">{row.status}</td><td className="p-3">{row.reviewed_at?formatApprovalDate(row.reviewed_at):"—"}</td><td className="p-3">{row.reviewed_by_name||"Propriétaire"}</td><td className="p-3">{row.execution_duration_ms!=null?`${row.execution_duration_ms} ms`:"—"}</td><td className={`p-3 ${row.execution_error?"text-red-700":"text-emerald-700"}`}>{row.execution_error||row.review_note||("Exécution terminée")}</td></tr>)}</tbody></table>{!history.length?<p className="p-5 text-center text-navy/45">Aucun historique.</p>:null}</div></section>:null}
  </div>;
}
