"use client";
import { useMemo,useState } from "react";
import { Archive,BookOpen,Copy,Eye,Plus,RotateCcw,Search,Star,X } from "lucide-react";
import type { LibraryItem } from "@/lib/document-library";

const categories=["toutes","lettre","courriel","procedure","guide","checklist","pdf"] as const;
type LibraryClient={id:string;full_name:string;file_reference:string|null};
export function LibraryManager({initialItems,clients}:{initialItems:LibraryItem[];clients:LibraryClient[]}){
  const[items,setItems]=useState(initialItems),[open,setOpen]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState<(typeof categories)[number]>("toutes"),[favoritesOnly,setFavoritesOnly]=useState(false),[showArchived,setShowArchived]=useState(false),[preview,setPreview]=useState<LibraryItem|null>(null),[busy,setBusy]=useState("");
  const[clientId,setClientId]=useState(clients[0]?.id||""),[renderedContent,setRenderedContent]=useState(""),[missingVariables,setMissingVariables]=useState<string[]>([]);
  const filtered=useMemo(()=>items.filter(item=>showArchived?item.status==="archived":item.status!=="archived").filter(item=>category==="toutes"||item.category===category).filter(item=>!favoritesOnly||item.is_favorite).filter(item=>{const haystack=[item.title,item.description,item.content,...item.tags].join(" ").toLocaleLowerCase("fr");return haystack.includes(query.trim().toLocaleLowerCase("fr"));}),[items,showArchived,category,favoritesOnly,query]);
  async function submit(formData:FormData){setError("");const response=await fetch("/api/admin/library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(formData))});const data=await response.json() as LibraryItem&{error?:string};if(!response.ok){setError(data.error||"Enregistrement impossible.");return}setItems(current=>[data,...current]);setOpen(false)}
  async function action(item:LibraryItem,type:"favorite"|"archive"|"restore"|"duplicate"){setBusy(item.id+type);setError("");const response=await fetch("/api/admin/library",{method:type==="duplicate"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(type==="duplicate"?{action:"duplicate",id:item.id}:{action:type,id:item.id,value:!item.is_favorite})});const data=await response.json() as LibraryItem&{error?:string};setBusy("");if(!response.ok){setError(data.error||"Modification impossible.");return}if(type==="duplicate")setItems(current=>[data,...current]);else setItems(current=>current.map(value=>value.id===data.id?data:value));}
  async function renderForClient(){if(!preview||!clientId)return;setBusy(preview.id+"render");const response=await fetch("/api/admin/library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"render",id:preview.id,clientId})});const data=await response.json() as{content?:string;missing?:string[];error?:string};setBusy("");if(!response.ok){setError(data.error||"Préparation impossible.");return;}setRenderedContent(data.content||"");setMissingVariables(data.missing||[]);}
  return <div className="space-y-6">
    <section className="rounded-[1.6rem] bg-white p-5 shadow-premium"><label className="text-xs font-black uppercase tracking-[.16em] text-navy/55">Dossier utilisé pour les variables<select value={clientId} onChange={event=>{setClientId(event.target.value);setRenderedContent("");}} className="mt-2 block w-full rounded-xl border border-navy/10 p-3 text-sm normal-case tracking-normal"><option value="">Sélectionner un client</option>{clients.map(client=><option key={client.id} value={client.id}>{client.full_name}{client.file_reference?` — ${client.file_reference}`:""}</option>)}</select></label>{preview?<button type="button" disabled={!clientId||Boolean(busy)} onClick={()=>void renderForClient()} className="mt-3 rounded-xl bg-canada px-4 py-3 text-sm font-black text-white disabled:opacity-40">Remplir automatiquement le modèle affiché</button>:<p className="mt-3 text-sm text-navy/45">Ouvrez l’aperçu d’un modèle, puis utilisez ce dossier pour remplir ses variables.</p>}</section>
    {renderedContent?<section className="rounded-[2rem] bg-white p-5 shadow-premium"><p className="text-xs font-black uppercase tracking-[.18em] text-canada">Aperçu client prêt à vérifier</p>{missingVariables.length?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">Champs sans donnée dans le CRM : {missingVariables.join(", ")}</p>:<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Toutes les variables du modèle ont été remplacées.</p>}<article className="mx-auto mt-5 min-h-[70vh] max-w-[680px] whitespace-pre-wrap border bg-white px-12 py-14 text-sm leading-7 text-navy shadow-xl"><header className="mb-10 border-b-2 border-gold pb-5"><strong className="text-2xl">ACCÈS CANADA</strong><p className="text-xs uppercase tracking-[.18em] text-navy/45">Document professionnel</p></header>{renderedContent}<footer className="mt-16 border-t pt-8 text-xs text-navy/45">Signature : ____________________ &nbsp;&nbsp; Date : ____________________</footer></article></section>:null}
    <section className="flex flex-col gap-5 rounded-[2rem] bg-navy p-7 text-white shadow-premium md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Base documentaire professionnelle</p><h1 className="mt-3 font-display text-4xl font-black">Bibliothèque documentaire</h1><p className="mt-3 max-w-2xl text-white/60">Recherchez, prévisualisez, dupliquez, versionnez et archivez les modèles réservés à l’administration.</p></div><button type="button" onClick={()=>setOpen(!open)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gold px-5 py-3 font-black text-navy"><Plus/>Nouveau modèle</button></section>
    {open?<form action={submit} className="grid gap-4 rounded-[2rem] bg-white p-6 shadow-premium"><input aria-label="Titre du modèle" name="title" required placeholder="Titre du modèle" className="rounded-xl border border-navy/15 p-3"/><select aria-label="Catégorie du modèle" name="category" className="rounded-xl border border-navy/15 p-3">{categories.slice(1).map(value=><option key={value} value={value}>{value}</option>)}</select><input aria-label="Tags" name="tags" placeholder="Tags séparés par des virgules" className="rounded-xl border border-navy/15 p-3"/><textarea aria-label="Description" name="description" placeholder="Description" className="rounded-xl border border-navy/15 p-3"/><textarea aria-label="Contenu du modèle" name="content" rows={10} placeholder="Contenu du modèle" className="rounded-xl border border-navy/15 p-3"/><button className="rounded-xl bg-navy px-5 py-3 font-black text-white">Enregistrer</button></form>:null}
    <section className="grid gap-3 rounded-[1.6rem] bg-white p-4 shadow-premium lg:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-4 top-3.5 h-5 w-5 text-navy/35"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher un titre, un tag ou du contenu…" className="w-full rounded-xl border border-navy/10 py-3 pl-12 pr-4 outline-none focus:border-gold"/></label><select value={category} onChange={event=>setCategory(event.target.value as typeof category)} className="rounded-xl border border-navy/10 px-4 py-3">{categories.map(value=><option key={value} value={value}>{value==="toutes"?"Toutes les catégories":value}</option>)}</select><div className="flex gap-2"><button onClick={()=>setFavoritesOnly(!favoritesOnly)} className={`rounded-xl px-4 py-3 text-sm font-black ${favoritesOnly?"bg-gold text-navy":"bg-ivory text-navy/65"}`}><Star className="mr-2 inline h-4 w-4"/>Favoris</button><button onClick={()=>setShowArchived(!showArchived)} className={`rounded-xl px-4 py-3 text-sm font-black ${showArchived?"bg-navy text-white":"bg-ivory text-navy/65"}`}><Archive className="mr-2 inline h-4 w-4"/>Archives</button></div></section>
    {error?<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>:null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><article key={item.id} className="rounded-[1.6rem] bg-white p-5 shadow-premium"><div className="flex items-start justify-between"><BookOpen className="text-gold"/><button title={item.is_favorite?"Retirer des favoris":"Ajouter aux favoris"} onClick={()=>action(item,"favorite")}><Star className={`h-5 w-5 ${item.is_favorite?"fill-gold text-gold":"text-navy/25"}`}/></button></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-gold/15 px-3 py-1 text-xs font-black uppercase">{item.category}</span><span className="rounded-full bg-navy/8 px-3 py-1 text-xs font-black">Version {item.version}</span>{item.status==="archived"?<span className="rounded-full bg-red-50 px-3 py-1 text-xs font-black text-red-700">Archivé</span>:null}</div><h2 className="mt-3 text-xl font-black">{item.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-navy/55">{item.description||"Aucune description."}</p><div className="mt-4 flex flex-wrap gap-1">{item.tags.map(tag=><span key={tag} className="rounded-full bg-ivory px-2 py-1 text-xs font-bold">{tag}</span>)}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-navy/8 pt-4"><button onClick={()=>setPreview(item)} className="rounded-lg bg-navy px-3 py-2 text-xs font-black text-white"><Eye className="mr-1 inline h-4 w-4"/>Aperçu</button><button disabled={busy.startsWith(item.id)} onClick={()=>action(item,"duplicate")} className="rounded-lg bg-gold/20 px-3 py-2 text-xs font-black text-navy"><Copy className="mr-1 inline h-4 w-4"/>Dupliquer</button><button disabled={busy.startsWith(item.id)} onClick={()=>action(item,item.status==="archived"?"restore":"archive")} className="rounded-lg bg-ivory px-3 py-2 text-xs font-black text-navy/65">{item.status==="archived"?<RotateCcw className="mr-1 inline h-4 w-4"/>:<Archive className="mr-1 inline h-4 w-4"/>}{item.status==="archived"?"Restaurer":"Archiver"}</button></div></article>)}</section>
    {!filtered.length?<p className="rounded-[2rem] bg-white p-8 text-center font-bold text-navy/45">Aucun modèle ne correspond aux filtres sélectionnés.</p>:null}
    {preview?<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-navy/70 p-4" onClick={()=>setPreview(null)}><article onClick={event=>event.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-[2rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-canada">Aperçu — version {preview.version}</p><h2 className="mt-2 text-3xl font-black text-navy">{preview.title}</h2></div><button onClick={()=>setPreview(null)} aria-label="Fermer"><X/></button></div><p className="mt-5 whitespace-pre-wrap rounded-2xl bg-ivory p-5 text-sm leading-7 text-navy/75">{preview.content||preview.description||"Ce modèle ne contient pas encore de contenu."}</p></article></div>:null}
  </div>;
}
